### ISSUE TITLE
Running StockExplorer example in a bokeh server

### ISSUE THREAD

**Issue by limx0** [holoviz/holoviz#101]
Hi, 

I am trying to run the StockExplorer example in a bokeh server but am not getting any interactivity. The plot and widgets show fine, but changes to widgets do not trigger any updates.

Source:
```python
import holoviews as hv
import pandas as pd
import panel as pp
import param
import parambokeh
from bokeh.sampledata import stocks
from bokeh.server.server import Server
from holoviews.operation.timeseries import rolling, rolling_outlier_std
from holoviews.streams import Stream

hv.notebook_extension('bokeh', mode='server')

def load_symbol(symbol, variable='adj_close', **kwargs):
    df = pd.DataFrame(getattr(stocks, symbol))
    df['date'] = df.date.astype('datetime64[ns]')
    return hv.Curve(df, ('date', 'Date'), variable)

stock_symbols = ['AAPL', 'IBM', 'FB', 'GOOG', 'MSFT']

class StockExplorer(Stream):
    rolling_window = param.Integer(default=10, bounds=(1, 365))

    symbol = param.ObjectSelector(default='AAPL', objects=stock_symbols)

    def view(self):
        stocks = hv.DynamicMap(load_symbol, kdims=[], streams=[self])

        # Apply rolling mean
        smoothed = rolling(stocks, streams=[self])

        # Find outliers
        outliers = rolling_outlier_std(stocks, streams=[self])
        return smoothed * outliers

def modify_doc(doc):
    explorer = StockExplorer()
    parambokeh.Widgets(explorer, continuous_update=True, callback=explorer.event, on_init=True, mode='server')
    panel = pp.Row(explorer, explorer.view())
    return panel.server_doc(doc=doc)


server = Server({'/': modify_doc}, port=0)
server.start()
server.show('/')
server.run_until_shutdown()
```
I have tried to adapt/combine examples from the "Creating interactive dashboards" and "Deploying a bokeh app" sections of pyviz/holoviews but am not having any luck. I may be doing something wrong on the `doc` side?

Worth noting, this works as expected in the notebook.

Am I missing something obvious?

**Comment by marcbernot** [comment]
At first I didn't manage to make interactivity work in the notebook by using these lines pasted from your code:
```
explorer = StockExplorer()
panel = pp.Row(explorer, explorer.view())
panel
```
Then I realized that the correct syntax is : 
`panel = pp.Row(explorer, explorer.view)`
And everything goes well in the notebook and in the server (with PyViz 0.9.12 but not with 0.9.13a0 I'll raise an issue about that)

Note that you don't need this line `parambokeh.Widgets(explorer, continuous_update=True, callback=explorer.event, on_init=True, mode='server') ` and that there is no "mode" argument in `hv.notebook_extension` so just `hv.extension('bokeh')` is fine.

**Comment by limx0** [comment]
Awesome, thanks @marcbernot.
