### ISSUE TITLE
Make the holoviz tutorial into an anaconda-project

### ISSUE THREAD

**Issue by ceball** [holoviz/holoviz#110]
We currently produce only a highly pinned conda package. That's ok, because holoviz isn't a library that's designed to be integrated into someone else's package (that's what the libraries underlying holoviz are for). But a highly pinned conda package can be difficult/annoying to install, except in a dedicated environment. So we suggest: `create env create -n holoviz-tutorial python=3.7 && conda activate holoviz-tutorial && conda install -c pyviz holoviz` followed by `holoviz examples` to get the examples. A nicer alternative might be a "conda env create (remote env file on anaconda.org or maybe github)" command. Or an anaconda project/similar.

Alternatively, we could say something like "conda install pyct && pyct holoviz examples && cd holoviz-examples && conda env create" (pyct having few dependencies and hence being easy to install).

**Comment by jsignell** [comment]
I like the idea of holoviz being not a package but an environment with the spec just in this github repo. `conda env create -f https://raw.githubusercontent.com/holoviz/holoviz/master/environment.yml`

**Comment by jsignell** [comment]
Just a note that there is no support for remote conda env spec files  at the moment. So I think we are stuck with packages.

**Comment by jbednar** [comment]
We are still using packages, but there are at least three viable alternatives to consider:

1. **anaconda-project**: Projects neatly package an environment, a set of .py  or .pynb files, and a way to fetch data, which covers precisely what the tutorial needs.  Plus we've already worked out (and continue to optimize) methods for capturing dependencies reproducibly in a way that can be upgraded later, which is also needed here.  Specific versions can easily then be archived from specific events. Moreover, if we use examples.pyviz.org to host the projects, the files will be individually git version controlled while also generating specific zip files when the contents change.  However, it doesn't fit _perfectly_ into examples.pyviz.org, as these literally are not examples but training material, and we also don't want a dozen different icons for it to pollute examples.pyviz.org unless it's in a separate section. Works well when we need to run training sessions based on AE5, and it would even let people run the tutorial themselves on examples.pyviz.org (though that might consume a good bit of computing power). We'd need a way to tell people to get the project and open it on their machine. Still seems like a viable option with a lot of advantages.
2. **conda create**: `conda create --file https://raw.githubusercontent.com/binder-examples/requirements/master/requirements.txt -n test` will build an environment from a remote specification, but it's not a conda spec, which could be painful.  It seems like it is possible to specify channels in that file, so maybe it would work.  We'd still need a way to distribute the .ipynb files meant for that environment, which is what the metapackage achieves.
3.  **conda env create**: `conda install anaconda-client -n base && conda env create jbednar/testy` -- for environments uploaded to anaconda.org (see below). Doesn't currently accept a full URL but does support remote conda env spec files.  Similar to the requirements.txt option in that it doesn't provide a way to get the notebooks.

Uploading environments to anaconda.org works as follows:
```
$ conda env export -n testy -f testy.yml
$ anaconda upload testy.yml 
...
environment located at:
https://anaconda.org/jbednar/testy
$ conda env remove -n testy
Remove all packages in environment /Users/jbednar/miniconda3/envs/testy:
$ conda env create jbednar/testy
SpecNotFound: Anaconda Client is required to interact with anaconda.org or an Anaconda API. Please run `conda install anaconda-client -n base`.
$ conda install anaconda-client -n base
Collecting package metadata (current_repodata.json): done
Solving environment: done
...
Executing transaction: done
$ conda env create jbednar/testy
Collecting package metadata (repodata.json): done
Solving environment: done
...
 To activate this environment, use
#
#     $ conda activate testy
$ 
```

**Comment by jbednar** [comment]
Oh, and a way to eliminate some of the problems with the metapackage `holoviz` being confusing (why do I get out of date packages? Is this how I am meant to install holoviz?  What is this package for?) is simply to rename the metapackage `holoviz-tutorial`.  A tutorial won't surprise anyone if it's pinned strictly, presumably, while `holoviz` being pinned does, and in practice we have not been updating `holoviz` pinning often enough for it to be useful as a guide to mutually compatible versions for purposes other than tutorials.

**Comment by ceball** [comment]
I think renaming the package from holoviz to holoviz-tutorial would be a good move (doesn't preclude other options in the future).

**Comment by jbednar** [comment]
I agree that renaming it would be an improvement, but I think I favor simply releasing an anaconda-project instead. Seems much simpler than making packages.

**Comment by jlstevens** [comment]
Making an anaconda-project out of the tutorial is a good idea regardless!

**Comment by jbednar** [comment]
When we do that, I propose that we re-release the `holoviz` package _unpinned_, so that it works as an easy way to install the latest versions of the holoviz tools (apart from geoviews, I think), without us ever having to update and release it again.

**Comment by jbednar** [comment]
Done!
