### ISSUE TITLE
Issue with tutorial

### ISSUE THREAD

**Issue by mrequena** [holoviz/holoviz#113]
I'm following the tutorial in: 
http://pyviz.org/tutorial/00_Setup.html

When I launch:
$ pyviz examples 
I get the error:
usage: pyviz [-h] [--download-sample-data [sample_data_dest]]
             [--install-examples [install_examples]]
pyviz: error: unrecognized arguments: examples

If I try:
$ pyviz --install-examples pyviz-examples
I get:
Downloading archive: 'https://github.com/pyviz/pyviz/archive/master.zip'
Download complete. Extracting
Traceback (most recent call last):
  File "/home/mmmm/anaconda3/bin/pyviz", line 10, in <module>
    sys.exit(main())
  File "/home/mmmm/anaconda3/lib/python3.6/site-packages/pyviz/cmd.py", line 99, in main
    install_examples(args.install_examples)
  File "/home/mmmm/anaconda3/lib/python3.6/site-packages/pyviz/cmd.py", line 67, in install_examples
    file_data = zf.read('{file_path}'.format(ref=ref, file_path=file_path))
  File "/home/mmmm/anaconda3/lib/python3.6/zipfile.py", line 1314, in read
    with self.open(name, "r", pwd) as fp:
  File "/home/mmmm/anaconda3/lib/python3.6/zipfile.py", line 1352, in open
    zinfo = self.getinfo(name)
  File "/home/mmmm/anaconda3/lib/python3.6/zipfile.py", line 1281, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named 'pyviz-master/README.rst' in the archive"

**Comment by ceball** [comment]
Sorry, the problem you're having is because we've just recently been moving things around. 

Could you report the output of conda list and conda info?

I suspect you installed pyviz using `-c pyviz` rather than `-c pyviz/label/dev`; pyviz.org was showing the wrong thing until very recently.

**Comment by ceball** [comment]
Actually, what I said above about using `-c pyviz/label/dev` won't help. I thought about it, and realized that the existing conda package is of course still using the previous pyviz command. 

So, we'll either need to release a new conda package, or restore material in the github repository to make the previous pyviz command work.

We now have automated tests that will catch this kind of issue with released packages. But they haven't yet run since we've made various recent changes (because they only run weekly)!

**Comment by mrequena** [comment]
I tried both and I got the same error. Following output is with -c pyviz/label/dev

In case it can help:
$ conda info

     active environment : pyviz-tutorial
    active env location : /home/mmmm/anaconda3/envs/pyviz-tutorial
            shell level : 1
       user config file : /home/mmmm/.condarc
 populated config files : 
          conda version : 4.5.11
    conda-build version : 3.10.5
         python version : 3.6.5.final.0
       base environment : /home/mmmm/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/mmmm/anaconda3/pkgs
                          /home/mmmm/.conda/pkgs
       envs directories : /home/mmmm/anaconda3/envs
                          /home/mmmm/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.18.4 CPython/3.6.5 Linux/4.15.0-36-generic ubuntu/18.04 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

and output from "conda list | grep pyviz":
# packages in environment at /home/mmmm/anaconda3/envs/pyviz-tutorial:
bokeh                     1.0.0dev6          pyhdd78535_0    pyviz/label/dev
datashader                0.6.8                      py_0    pyviz/label/dev
geoviews                  1.5.4a6                    py_0    pyviz/label/dev
geoviews-core             1.5.4a6                    py_0    pyviz/label/dev
holoviews                 1.11.0a4                   py_0    pyviz/label/dev
hvplot                    0.2.1                      py_0    pyviz/label/dev
panel                     0.1.0a3                    py_0    pyviz/label/dev
param                     1.8.0a2                    py_0    pyviz/label/dev
parambokeh                0.2.3                      py_0    pyviz/label/dev
paramnb                   2.0.4                      py_0    pyviz/label/dev
phantomjs                 2.1.1                         0    pyviz/label/dev
pyct                      0.4.5                      py_0    pyviz/label/dev
pyct-core                 0.4.5                      py_0    pyviz/label/dev
pyviz                     0.9.12                     py_0    pyviz/label/dev
pyviz_comms               0.6.0                      py_0    pyviz/label/dev
rise                      5.3.0                    py36_0    pyviz/label/dev

**Comment by ceball** [comment]
To make the existing pyviz command work (i.e. would help anyone who already has the pyviz conda package and hasn't already downloaded the tutorial), it looks like the following would need to be restored on github:

```
example_assets = ['README.rst',
                  'apps/',
                  'data/',
                  'datasets.yml',
                  'exercises/',
                  'images/',
                  'notebooks/']
```

(from https://github.com/pyviz/pyviz/blob/512d3d642795f60151cc03e81e41cd35990506b1/pyviz/cmd.py#L38 )

Maybe it could be done with symlinks?

I think I favor just releasing a new conda package (though this won't help anyone who has a previous package and needs to run the download examples command - they'd need to update to the newer package).

What does everyone else think?

**Comment by ceball** [comment]
I've tagged to make a new dev package of pyviz (which launches a build on travis). I'll be back in about an hour, so will post back here with an update on how that went.

**Comment by jbednar** [comment]
I favor a new conda package as well.

**Comment by ceball** [comment]
There's a new package on pyviz/label/dev, but I can;t try it out yet.

@mrequena, if you have time, you could try doing `conda install -c pyviz/label/dev pyviz` to get the new pyviz package (currently 0.9.13a0), and then re-try the `pyviz examples` command (as on pyviz.org)?

Thanks for reporting the issue. The tests wouldn't have noticed it for another 3 days. I suppose I could make them run more frequently, I just feel bad about using too much of the free resources from travis and appveyor...

**Comment by mrequena** [comment]
After updating the pyviz package with:
conda install -c pyviz/label/dev pyviz

I can run: pyviz examples
and I can launch the jupyter notebook.

Thanks!
