### ISSUE TITLE
01 Workflow error bar range broken

### ISSUE THREAD

**Issue by jbednar** [holoviz/holoviz#117]
Used to work; not sure when it stopped autoranging reasonably:

![image](https://user-images.githubusercontent.com/1695496/46637499-09e30680-cb22-11e8-8718-e798cc51796d.png)

**Comment by philippjfr** [comment]
That's pretty bizarre.

**Comment by philippjfr** [comment]
Turned out to be a bug which was itself covered up by another bug.

**Comment by philippjfr** [comment]
Fixed on holoviews master.
