### ISSUE TITLE
Windrose plots 

### ISSUE THREAD

**Issue by rr5577** [holoviz/holoviz#123]
I´d like to do Windrose (that i ultimately would like to link to geoviews maps in a dashboard) plots with pyviz, but I´m not sure if there´s a straightforward way to do it with bokeh or holoviews.

I think it could be done using AnnularWedges in bokeh, however according to this [stackoverflow answer](https://stackoverflow.com/questions/44423704/how-to-convert-a-matplotlib-pyplot-to-a-bokeh-plot), there´s no radial axis in bokeh as of 0.13.
In holoviewsI found radial heatmaps, but if I´m not mistaken it always creates a "filled" circle, and i don´t think that´d work for a windrose:
![image](https://user-images.githubusercontent.com/31547476/47134960-d4bb7e80-d2ae-11e8-812c-41c4313bb78a.png)

I think matplotlib would work for creating a windrose, but then I´d loose the interactivity. Also I´m not sure if you can mix/link bokeh, geoviews with matplotlib in a dashboard?

**Comment by jbednar** [comment]
You can mix bokeh, geoviews, matplotlib, and just about anything else in a [Panel](http://panel.pyviz.org) dashboard: https://anaconda.org/jbednar/panel_gapminders

And you can link the matplotlib plots to other plots in one direction, e.g. clicking or making selections in a Bokeh-based plot that updates the matplotlib plot.  But the resulting matplotlib plot will just be a PNG, so you wouldn't be able to select or interact directly with the matplotlib plot and affect other plots.  So whether the matplotlib version will work for you depends on precisely what interactivity you need.

I would guess that you could follow some AnnularWedges example code and make this plot in Bokeh, though it would be a lot easier to do if someone would go ahead and add full radial axis support to Bokeh.

**Comment by rr5577** [comment]
Thanks for these tips, I think Panel sounds like a great tool for what I´m trying to do!

**Comment by jsignell** [comment]
I am going to close this, but if you ended up creating something that is sharable @rr5577 please open a PR at https://github.com/pyviz-topics/contrib
