### ISSUE TITLE
Standardize on a pyviz console command

### ISSUE THREAD

**Issue by jlstevens** [holoviz/holoviz#129]
Currently there seems to be a proliferation of console scripts, e.g for `holoviews`, `geoviews`, `panel` etc. As every pyviz project is likely to have user installable examples, this suggests that if we continue down this path, we will end up with a console script for every pyviz project which seems rather excessive to me.

As I understand it, the alternative is to use `pyct` directly but this is not really a name that means much to users (and not another name we really want to introduce them to). What people will have heard of is `pyviz` and a single console script that works across all pyviz projects seems a lot easier to justify (and a way to make sure everything is very consistent)

Instead of lots of console scripts, I would prefer something like:

```
pyviz geoviews examples
```

In this example, `pyviz` is the entry point, the next argument is the sub-command (addressing the pyviz subproject) and then what follows is a common interface between all the projects.

I see a couple of options how we could achieve this:

1) Offer a `pyviz_core` package which has very lightweight dependencies and is very easy to install. It offers the `pyviz` console script and can be made a dependency of all pyviz project (as it is small and pure Python with no problematic dependencies).

2) Rename `pyct` to `pyviz_core`.

I can also imagine it being `pyviz_cmd` if the main purpose is the common command-line interface across pyviz projects.

**Comment by jbednar** [comment]
I'd be happy with this approach.  For option 1, would pyviz_core depend on pyct?  What else would be in pyviz_core besides this?

**Comment by jlstevens** [comment]
Another name for it, if it is just the CLI could be `pyviz_cli`.

**Comment by jlstevens** [comment]
Note that the idea here is to keep the common interface between the projects in the `pyviz` commands. It doesn't mean pyviz projects can't have their own console script, e.g we will still want `panel serve`. What it does mean is that not every pyviz project will need a console script to do some of the most standard operations (e.g installing examples).

**Comment by jsignell** [comment]
I didn't mean that `pyct` should be exposed to users. The console scripts are just wrappers around `pyct`:

https://github.com/pyviz/datashader/blob/17629bd82708499beb0b990d7f092fd68ea3d172/datashader/__main__.py#L1-L12

I guess I think that current state of affairs is fine.

**Comment by jsignell** [comment]
It seems like your proposal is more verbose and I don't understand what the benefit are other than getting rid of a couple lines of boilerplate.

**Comment by jsignell** [comment]
If it's just an issue of not wanting to add more console scripts, then why have a console script at all when we could just import data using `load_dataset` or something like they do in xarray, seaborn,..

**Comment by jbednar** [comment]
I don't mind either way.  Either way, pyct would be the implementation for these commands, with very little setup for each project (apart from panel).  The advantages I see for Jean-Luc's proposal are:

- users only have a single command ("pyviz") added to their shell path regardless of how many pyviz projects are installed
- each project just depends on pyviz_core rather than needing any code in setup.py to set up the console commands
- if a project (e.g. panel) needs to do some of its own console commands, doing so will be entirely independent of the implementation of the pyct-based commands.

The advantages I see for the current approach of having a console command for each library are:

- shorter commands for users to type
- more obvious commands for users -- avoiding users having to worry about what "pyviz" or "pyct" are when they are installing any given package
- it's already what we're doing

On balance I prefer having a console command for each library; I think it's cleaner, personally.  But I don't strongly object to Jean-Luc's proposal, as those advantages are also real.  Sounds like we have two votes for the status quo (one from Julia, and a weak one from me), and one vote against the status quo.  @philippjfr?

**Comment by philippjfr** [comment]
Maybe I'm not following completely but I'm also having trouble seeing the benefits or rather the stated benefits don't seem particularly compelling to me. Unless I'm misunderstanding things each project will have a bit of boilerplate which calls the appropriate commands in pyct so it's not duplicating all of the CLI code each time. If we are in fact duplicating all of the CLI code each time we should address that issue and ensure that each project only has minimal boilerplate code to call the appropriate command in pyct or where ever. 

Having shorter commands seems preferable and I also don't think a user of any one of our libraries necessarily needs or wants to know about the overall pyviz ecosystem. The only thing I would strongly urge is that the console commands for each library are as uniform as possible, which should already be the case or would be the case if each entrypoint just calls some upstream code in pyct or where ever that lives.

**Comment by jlstevens** [comment]
All I know is that a user, I would be very annoyed if I found every python library I installed felt entitled to its own console script, especially if the console script does very little. The command line is another namespace you should be respectful of and avoid polluting.

**Comment by philippjfr** [comment]
>All I know is that a user, I would be very annoyed if I found every python library I installed felt entitled to its own console script, especially if the console script does very little

Don't find that very compelling personally. I'd estimate that my commandline tab-completes about 2500 commands, I'll never notice an extra 5-10 items and thanks to conda/virtualenv/pipenv environments none of these are added globally.

**Comment by jbednar** [comment]
Ok, it's not a consensus, but that's about as close as we're likely to get -- two yeses and a weak yes in favor of the status quo of separate console scripts.  So please let's go with that and not discuss it further unless something important changes. And of course let's make sure that very little boilerplate will be needed per project; the real implementation will still be in pyct.
