### ISSUE TITLE
Can I pay for professional support?

### ISSUE THREAD

**Issue by zouhx11** [holoviz/holoviz#143]
I love pyviz and it looks great. However, sometimes I still can't figure out all the details to get what I want, and I want to pay money to save time because I'm not good at programming. Will Anaconda provide such service? Thanks!

**Comment by jbednar** [comment]
Anaconda provides consulting services for large corporate or government projects using our commercial or open-source software, but we don't have anything suitable for individual users.  You could try www.opensourceanswers.com or maybe [quansight.com](https://www.quansight.com) ...
