### ISSUE TITLE
Centralized location for easy pyviz contributions

### ISSUE THREAD

**Issue by jlstevens** [holoviz/holoviz#147]
One of the most difficult things when authoring documentation is coming up with good, simple examples. This is a problem when trying to author tutorial material, user guides, gallery examples and so on.

Currently we have no good, consistent way for pyviz users to share demos and examples with each other. For instance, @philippjfr and @jbednar use anaconda.org accounts to share notebooks, some of our users have little github repos for pyviz examples, some use gists and nbviewer for that etc.

I would really like to have a centralized location where all pyviz users can share various ideas and examples of what is possible with these tools. 

This idea isn't new, I had hoped [holoviews-contrib](https://github.com/ioam/holoviews-contrib) could fulfill this role but unfortunately that repo never took off. The goal of this issue is to brainstorm ways to make this idea work.

Here are some of the features I would like:

* Very low barrier to entry. We want to make it as easy as possible for anyone to capture any cool little snippet of code. On [holoviews-contrib](https://github.com/ioam/holoviews-contrib)  the idea was to use the GitHub wiki for this purpose.
* A route for a rough example to gradually transform into something polished to use in the official docs or on the website.
* A way for people to just submit *ideas* for simple example that are meaningful or illustrative. Good examples use minimal dependencies and don't need much code.
* A way to add/suggest new datasets. We can add small examples directly to the holoviews repo (say) but we can also add bigger examples on S3 which we can fetch via intake.

## Possible Approaches

* A new GitHub repo on the `pyviz-topics` organization called contrib. This would be a second attempt at [holoviews-contrib](https://github.com/ioam/holoviews-contrib) broadened to all of pyviz. We would have to think about how we could make such a repo more successful this time around.
* A common/shared anaconda.org account where people can upload anaconda projects or notebooks. Can you have such an account that anyone can push to?
* GitHub gists?
* A simple web interface where people could upload stuff into our public S3 bucket?

My general feeling is that our users have plenty of interesting ideas that should be more widely disseminated and that we could use to avoid the pain of trying to come up with new examples from scratch over and over again.

Lastly, I feel that even if such a resource were only used by the pyviz devs without much user adoption, this would be an improvement over the current situation.

**Comment by jbednar** [comment]
Plus our users come from many different domains where we are not experts, and it's very helpful to see what they come up with.  Sounds reasonable, and I'd add that a github repo has the advantage of being able to open issues easily with just ideas and sketches, and PRs for more concrete stuff.   Anaconda.org has the advantage of being dead simple to upload a notebook or a project, but I don't think it has a way to have issues.  Not sure if anaconda.org can upload from a file requestor, but if not we could maybe have a web wrapper to do that even easier.

**Comment by jlstevens** [comment]
Probably worth mentioning: https://github.com/bokeh/share.bokeh.org

**Comment by jsignell** [comment]
Does examples.pyviz.org fill this need now?

**Comment by jbednar** [comment]
Sort of.  It's definitely a place for collecting any sort of examples.  However, it makes certain assumptions about reproducibility, structure, and format that are necessary for delivering things as live examples, which are important for us to be able to maintain working code, but may be a barrier to entry for many use cases.  That said, maybe we don't need to solve the things that aren't solved by examples.pyviz.org -- maybe that's the minimum standard that anything we really want to preserve needs to achieve, and anything else may as well be in some random notebook on nbviewer, some random git or gist, or anaconda.org -- the Wild West can stay the Wild West, and examples.pyviz.org can be for anything mature enough to really capture for sharing in a reliable, repeatable way. So in that sense, maybe close this?

**Comment by jsignell** [comment]
Ok I think that makes sense. If people can give us a notebook and environment, we can help them get their example added.
