### ISSUE TITLE
Following tutorial setup, the notebook doesn't launch

### ISSUE THREAD

**Issue by michaelaye** [holoviz/holoviz#150]
After executing `jupyter notebook` inside the `pyviz-examples` folder, I get this:

```bash
[C 15:46:02.512 NotebookApp] Bad config encountered during initialization:
[C 15:46:02.512 NotebookApp] The 'kernel_spec_manager_class' trait of <notebook.notebookapp.NotebookApp object at 0x10fcff278> instance must be a type, but 'nb_conda_kernels.CondaKernelSpecManager' could not be imported
```

**Comment by michaelaye** [comment]
Installing nb_conda_kernels solves this.

**Comment by jlstevens** [comment]
Sounds like it was an issue in your environment and not with the pyviz dependencies? I'll close this issue but I am happy to reopen if you can reproduce this in a clean environment.

**Comment by michaelaye** [comment]
yeah, sorry, my env was clean, following your instructions, but I have a reference to the `nb_conda_kernels` manager class in my `~/.jupyter/jupyter_config.json` file which I forgot about.
