### ISSUE TITLE
Tutorial 01: groupby 'State' fails

### ISSUE THREAD

**Issue by michaelaye** [holoviz/holoviz#151]
<img width="875" alt="screenshot 2019-01-26 17 11 57" src="https://user-images.githubusercontent.com/69774/51794332-a1319f80-218d-11e9-9e77-c0d0419eda64.png">

`KeyError: "Dimension 'State' not found."`

**Comment by philippjfr** [comment]
Could you confirm your version of pandas? There are some major incompatibilities with pandas 0.24.0 which was just released.

**Comment by michaelaye** [comment]
Aha! That explains why it suddenly works when I switch to my standard py37 env that still has pandas 0.23.4. The `pyviz-examples` env I created today has automatically received pandas 0.24.0 so I guess you need to pin pandas to <0.24 for that to work.

**Comment by philippjfr** [comment]
We're working on getting a compatible holoviews version out by tomorrow.
