### ISSUE TITLE
Does pyviz/holoviews support python IDEs, like pyCharm?

### ISSUE THREAD

**Issue by pengfeiWangPFW** [holoviz/holoviz#161]
I am writing a simple GUI with python tkinter/Qt to do some data exploration. And I like the rich features of pyViz very much, but I don't how to embed the pyViz in python IDEs or use it in the GUI. Is there any example for me to get some clue?

**Comment by jsignell** [comment]
We tend to use browser based GUIs. You might be interested in taking a look at [panel](https://panel.pyviz.org) to see if that would meet your needs.

**Comment by jbednar** [comment]
That said, we do expect to improve our PyCharm support over time, it just hasn't previously been a priority.

**Comment by pengfeiWangPFW** [comment]
Thank you for your update. I will check the panel instead then.
