### ISSUE TITLE
Stack Trace in A2_Dashboard_Workflow

### ISSUE THREAD

**Issue by gnfrazier** [holoviz/holoviz#186]
In the current build of the documentation [https://pyviz.org/tutorial/A2_Dashboard_Workflow.html ](https://pyviz.org/tutorial/A2_Dashboard_Workflow.html ) the code block

``` Python
%time df = dd.read_parquet('../data/nyc_taxi_wide.parq', engine='fastparquet').persist()
print(len(df))
df.head(2)
```

Is displaying a stack trace:

> NameError                                 Traceback (most recent call last)
> <ipython-input-2-9cc184f25852> in <module>
>      1 get_ipython().run_line_magic('time', "df = dd.read_parquet('../data/nyc_taxi_wide.parq', > engine='fastparquet').persist()")
> ----> 2 print(len(df))
>      3 df.head(2)

> NameError: name 'df' is not defined

**Comment by jsignell** [comment]
Thanks for the report! I rebuilt the site so it's fixed now. You might need to do a hard refresh to see the changes.
