### ISSUE TITLE
Installation fails with `UnsatisfiableError: The following specifications were found to be incompatible with each other`

### ISSUE THREAD

**Issue by asmith26** [holoviz/holoviz#193]
Following the instructions at https://holoviz.org/installation.html, at step 2 I'm getting:

```
$  conda install -c pyviz/label/dev holoviz
Collecting package metadata (current_repodata.json): done
Solving environment: failed
Collecting package metadata (repodata.json): done
Solving environment: failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

  - holoviz -> bokeh[version='>=1.2.0'] -> numpy[version='>=1.7.1'] -> blas==1.0=mkl
  - holoviz -> bokeh[version='>=1.2.0'] -> numpy[version='>=1.7.1'] -> libgcc-ng[version='>=7.3.0']
  - holoviz -> bokeh[version='>=1.2.0'] -> numpy[version='>=1.7.1'] -> libgfortran-ng[version='>=7,<8.0a0']
  - holoviz -> bokeh[version='>=1.2.0'] -> numpy[version='>=1.7.1'] -> mkl[version='>=2019.3,<2020.0a0'] -> intel-openmp
  - holoviz -> bokeh[version='>=1.2.0'] -> numpy[version='>=1.7.1'] -> python[version='>=3.6,<3.7.0a0'] -> libstdcxx-ng[version='>=7.3.0']
  - holoviz -> cffi
  - holoviz -> dask[version='>=0.18.2'] -> pandas[version='>=0.21.0']
  - holoviz -> dask[version='>=0.18.2'] -> toolz[version='>=0.7.3']
  - holoviz -> datashader[version='>=0.7.0'] -> param[version='>=1.6.0']
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> conda[version='>=4.4'] -> conda-build[version='>=3'] -> beautifulsoup4 -> soupsieve -> backports.functools_lru_cache
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> conda[version='>=4.4'] -> conda-build[version='>=3'] -> conda-verify[version='>=3.1.0'] -> backports.tempfile -> backports.weakref
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> conda[version='>=4.4'] -> conda-build[version='>=3'] -> conda-verify[version='>=3.1.0'] -> future
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> conda[version='>=4.4'] -> conda-build[version='>=3'] -> filelock
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> conda[version='>=4.4'] -> conda-build[version='>=3'] -> glob2[version='>=0.6']
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> conda[version='>=4.4'] -> conda-build[version='>=3'] -> patchelf
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> conda[version='>=4.4'] -> conda-build[version='>=3'] -> pkginfo
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> conda[version='>=4.4'] -> conda-build[version='>=3'] -> py-lief -> liblief==0.9.0=h7725739_2
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> conda[version='>=4.4'] -> conda-env[version='>=2.6']
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> conda[version='>=4.4'] -> conda-package-handling[version='>=1.3.0'] -> libarchive[version='>=3.3.3'] -> lz4-c[version='>=1.8.1.2,<1.9.0a0']
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> conda[version='>=4.4'] -> conda-package-handling[version='>=1.3.0'] -> libarchive[version='>=3.3.3'] -> lzo[version='>=2.10,<3.0a0']
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> conda[version='>=4.4'] -> conda-package-handling[version='>=1.3.0'] -> python-libarchive-c
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> conda[version='>=4.4'] -> conda-package-handling[version='>=1.3.0'] -> tqdm
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> conda[version='>=4.4'] -> pycosat[version='>=0.6.3']
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> conda[version='>=4.4'] -> ruamel_yaml[version='>=0.11.14,<0.16']
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> doit -> pyinotify
  - holoviz -> datashader[version='>=0.7.0'] -> scikit-image -> matplotlib[version='>=2.0.0'] -> subprocess32
  - holoviz -> datashader[version='>=0.7.0'] -> scikit-image -> networkx[version='>=1.8']
  - holoviz -> datashader[version='>=0.7.0'] -> scikit-image -> scipy[version='>=0.17']
  - holoviz -> datashader[version='>=0.7.0'] -> xarray[version='>=0.9.6']
  - holoviz -> fastparquet[version='>=0.2.1']
  - holoviz -> holoviews[version='>=1.12.3'] -> ipython[version='>=5.4.0']
  - holoviz -> holoviews[version='>=1.12.3'] -> notebook
  - holoviz -> holoviews[version='>=1.12.3'] -> panel
  - holoviz -> hvplot[version='>=0.4.0']
  - holoviz -> ipywidgets
  - holoviz -> netcdf4
  - holoviz -> phantomjs
  - holoviz -> python-snappy
  - holoviz -> rise
  - holoviz -> selenium
  - holoviz -> streamz
```

I was able to successfully install this (prior to the rename to holoviz if it helps). Using Ubuntu 16.04, conda 4.7.5

**Comment by meverson86** [comment]
I'm also having the same issue using lubuntu 18.04 and conda 4.7.5

UnsatisfiableError: The following specifications were found to be incompatible with each other:

  - holoviz -> bokeh[version='>=1.2.0'] -> jinja2[version='>=2.7'] -> markupsafe[version='>=0.23'] -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex=[build=main]
  - holoviz -> bokeh[version='>=1.2.0'] -> jinja2[version='>=2.7'] -> markupsafe[version='>=0.23'] -> python[version='>=3.6,<3.7.0a0'] -> libstdcxx-ng[version='>=7.3.0']
  - holoviz -> bokeh[version='>=1.2.0'] -> jinja2[version='>=2.7'] -> markupsafe[version='>=0.23'] -> python[version='>=3.6,<3.7.0a0'] -> ncurses[version='>=6.1,<7.0a0']
  - holoviz -> bokeh[version='>=1.2.0'] -> jinja2[version='>=2.7'] -> markupsafe[version='>=0.23'] -> python[version='>=3.6,<3.7.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a'] -> ca-certificates
  - holoviz -> bokeh[version='>=1.2.0'] -> jinja2[version='>=2.7'] -> markupsafe[version='>=0.23'] -> python[version='>=3.6,<3.7.0a0'] -> pip -> setuptools -> certifi[version='>=2016.09']
  - holoviz -> bokeh[version='>=1.2.0'] -> jinja2[version='>=2.7'] -> markupsafe[version='>=0.23'] -> python[version='>=3.6,<3.7.0a0'] -> pip -> wheel
  - holoviz -> bokeh[version='>=1.2.0'] -> jinja2[version='>=2.7'] -> markupsafe[version='>=0.23'] -> python[version='>=3.6,<3.7.0a0'] -> tk[version='>=8.6.8,<8.7.0a0'] -> zlib[version='>=1.2.11,<1.3.0a0']
  - holoviz -> bokeh[version='>=1.2.0'] -> numpy[version='>=1.7.1'] -> blas==1.0=mkl
  - holoviz -> bokeh[version='>=1.2.0'] -> numpy[version='>=1.7.1'] -> libgfortran-ng[version='>=7,<8.0a0']
  - holoviz -> bokeh[version='>=1.2.0'] -> numpy[version='>=1.7.1'] -> mkl[version='>=2019.3,<2020.0a0'] -> intel-openmp
  - holoviz -> bokeh[version='>=1.2.0'] -> packaging[version='>=16.8'] -> pyparsing
  - holoviz -> bokeh[version='>=1.2.0'] -> packaging[version='>=16.8'] -> six
  - holoviz -> bokeh[version='>=1.2.0'] -> python-dateutil[version='>=2.1']
  - holoviz -> bokeh[version='>=1.2.0'] -> tornado[version='>=4.3'] -> backports_abc[version='>=0.4']
  - holoviz -> bokeh[version='>=1.2.0'] -> tornado[version='>=4.3'] -> futures
  - holoviz -> bokeh[version='>=1.2.0'] -> tornado[version='>=4.3'] -> singledispatch
  - holoviz -> bokeh[version='>=1.2.0'] -> tornado[version='>=4.3'] -> ssl_match_hostname -> backports
  - holoviz -> cffi
  - holoviz -> dask[version='>=0.18.2'] -> pandas[version='>=0.21.0']
  - holoviz -> datashader[version='>=0.7.0'] -> numba[version='>=0.37.0'] -> funcsigs
  - holoviz -> datashader[version='>=0.7.0'] -> numba[version='>=0.37.0'] -> llvmlite[version='>=0.29.0,<0.30.0a0'] -> enum34
  - holoviz -> datashader[version='>=0.7.0'] -> numba[version='>=0.37.0'] -> tbb[version='>=2018.0.5']
  - holoviz -> datashader[version='>=0.7.0'] -> param[version='>=1.6.0']
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> conda[version='>=4.4'] -> conda-build[version='>=3'] -> beautifulsoup4 -> soupsieve -> backports.functools_lru_cache
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> conda[version='>=4.4'] -> conda-build[version='>=3'] -> conda-verify[version='>=3.1.0'] -> backports.tempfile -> backports.weakref
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> conda[version='>=4.4'] -> conda-build[version='>=3'] -> conda-verify[version='>=3.1.0'] -> future
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> conda[version='>=4.4'] -> conda-build[version='>=3'] -> contextlib2
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> conda[version='>=4.4'] -> conda-build[version='>=3'] -> filelock
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> conda[version='>=4.4'] -> conda-build[version='>=3'] -> glob2[version='>=0.6']
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> conda[version='>=4.4'] -> conda-build[version='>=3'] -> patchelf
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> conda[version='>=4.4'] -> conda-build[version='>=3'] -> pkginfo
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> conda[version='>=4.4'] -> conda-build[version='>=3'] -> py-lief -> liblief==0.9.0=h7725739_2
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> conda[version='>=4.4'] -> conda-build[version='>=3'] -> scandir
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> conda[version='>=4.4'] -> conda-env[version='>=2.6']
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> conda[version='>=4.4'] -> conda-package-handling[version='>=1.3.0'] -> libarchive[version='>=3.3.3'] -> bzip2[version='>=1.0.6,<2.0a0']
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> conda[version='>=4.4'] -> conda-package-handling[version='>=1.3.0'] -> libarchive[version='>=3.3.3'] -> lz4-c[version='>=1.8.1.2,<1.9.0a0']
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> conda[version='>=4.4'] -> conda-package-handling[version='>=1.3.0'] -> libarchive[version='>=3.3.3'] -> lzo[version='>=2.10,<3.0a0']
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> conda[version='>=4.4'] -> conda-package-handling[version='>=1.3.0'] -> python-libarchive-c
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> conda[version='>=4.4'] -> conda-package-handling[version='>=1.3.0'] -> tqdm
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> conda[version='>=4.4'] -> pycosat[version='>=0.6.3']
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> conda[version='>=4.4'] -> pyopenssl[version='>=16.2.0'] -> cryptography[version='>=2.2.1'] -> asn1crypto[version='>=0.21.0']
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> conda[version='>=4.4'] -> pyopenssl[version='>=16.2.0'] -> cryptography[version='>=2.2.1'] -> cryptography-vectors=2.3
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> conda[version='>=4.4'] -> pyopenssl[version='>=16.2.0'] -> cryptography[version='>=2.2.1'] -> idna[version='>=2.1']
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> conda[version='>=4.4'] -> pyopenssl[version='>=16.2.0'] -> cryptography[version='>=2.2.1'] -> ipaddress
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> conda[version='>=4.4'] -> ruamel_yaml[version='>=0.11.14,<0.16']
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> doit -> configparser
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> doit -> pyinotify
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> pluggy -> importlib_metadata[version='>=0.12'] -> pathlib2
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> pluggy -> importlib_metadata[version='>=0.12'] -> zipp[version='>=0.5']
  - holoviz -> datashader[version='>=0.7.0'] -> pyct -> py
  - holoviz -> datashader[version='>=0.7.0'] -> scikit-image -> matplotlib[version='>=2.0.0'] -> functools32
  - holoviz -> datashader[version='>=0.7.0'] -> scikit-image -> matplotlib[version='>=2.0.0'] -> subprocess32
  - holoviz -> datashader[version='>=0.7.0'] -> scikit-image -> networkx[version='>=1.8'] -> decorator[version='>=4.3.0']
  - holoviz -> datashader[version='>=0.7.0'] -> scikit-image -> scipy[version='>=0.17']
  - holoviz -> datashader[version='>=0.7.0'] -> testpath[version='<0.4']
  - holoviz -> datashader[version='>=0.7.0'] -> xarray[version='>=0.9.6']
  - holoviz -> fastparquet[version='>=0.2.1'] -> pytest -> atomicwrites[version='>=1.0']
  - holoviz -> fastparquet[version='>=0.2.1'] -> pytest -> attrs[version='>=17.4.0']
  - holoviz -> fastparquet[version='>=0.2.1'] -> pytest -> more-itertools[version='>=4.0']
  - holoviz -> fastparquet[version='>=0.2.1'] -> pytest -> wcwidth
  - holoviz -> fastparquet[version='>=0.2.1'] -> thrift[version='>=0.11.0']
  - holoviz -> holoviews[version='>=1.12.3'] -> ipython[version='>=5.4.0'] -> pygments
  - holoviz -> holoviews[version='>=1.12.3'] -> ipython[version='>=5.4.0'] -> traitlets[version='>=4.2'] -> ipython_genutils
  - holoviz -> holoviews[version='>=1.12.3'] -> notebook -> ipykernel -> jupyter_client -> jupyter_core
  - holoviz -> holoviews[version='>=1.12.3'] -> notebook -> ipykernel -> jupyter_client -> pyzmq[version='>=13'] -> zeromq[version='>=4.3.1,<4.4.0a0'] -> libsodium[version='>=1.0.16,<1.0.17.0a0']
  - holoviz -> holoviews[version='>=1.12.3'] -> notebook -> nbconvert -> bleach -> html5lib[version='>=0.99999999pre,!=1.0b1,!=1.0b2,!=1.0b3,!=1.0b4,!=1.0b5,!=1.0b6,!=1.0b7,!=1.0b8']
  - holoviz -> holoviews[version='>=1.12.3'] -> notebook -> nbconvert -> bleach -> webencodings
  - holoviz -> holoviews[version='>=1.12.3'] -> notebook -> nbconvert -> defusedxml
  - holoviz -> holoviews[version='>=1.12.3'] -> notebook -> nbconvert -> entrypoints[version='>=0.2.2']
  - holoviz -> holoviews[version='>=1.12.3'] -> notebook -> nbconvert -> mistune[version='>=0.8.1']
  - holoviz -> holoviews[version='>=1.12.3'] -> notebook -> nbconvert -> nbformat[version='>=4.4'] -> jsonschema[version='>=2.4,!=2.5.0'] -> pyrsistent[version='>=0.14.0']
  - holoviz -> holoviews[version='>=1.12.3'] -> notebook -> nbconvert -> pandoc[version='>=1.12.1'] -> gmp
  - holoviz -> holoviews[version='>=1.12.3'] -> notebook -> nbconvert -> pandocfilters[version='>=1.4.1']
  - holoviz -> holoviews[version='>=1.12.3'] -> notebook -> prometheus_client -> twisted -> appdirs[version='>=1.4.0']
  - holoviz -> holoviews[version='>=1.12.3'] -> notebook -> prometheus_client -> twisted -> automat[version='>=0.3.0']
  - holoviz -> holoviews[version='>=1.12.3'] -> notebook -> prometheus_client -> twisted -> bcrypt
  - holoviz -> holoviews[version='>=1.12.3'] -> notebook -> prometheus_client -> twisted -> constantly[version='>=15.1']
  - holoviz -> holoviews[version='>=1.12.3'] -> notebook -> prometheus_client -> twisted -> h2[version='>=3.0,<4.0'] -> hpack[version='>=2.3,<4']
  - holoviz -> holoviews[version='>=1.12.3'] -> notebook -> prometheus_client -> twisted -> h2[version='>=3.0,<4.0'] -> hyperframe[version='>=5.1.0,<6']
  - holoviz -> holoviews[version='>=1.12.3'] -> notebook -> prometheus_client -> twisted -> hyperlink[version='>=17.1.1']
  - holoviz -> holoviews[version='>=1.12.3'] -> notebook -> prometheus_client -> twisted -> incremental[version='>=16.10.1']
  - holoviz -> holoviews[version='>=1.12.3'] -> notebook -> prometheus_client -> twisted -> priority[version='>=1.1.0,<2.0']
  - holoviz -> holoviews[version='>=1.12.3'] -> notebook -> prometheus_client -> twisted -> pyasn1
  - holoviz -> holoviews[version='>=1.12.3'] -> notebook -> prometheus_client -> twisted -> pyhamcrest[version='>=1.9.0']
  - holoviz -> holoviews[version='>=1.12.3'] -> notebook -> prometheus_client -> twisted -> pyobjc-core
  - holoviz -> holoviews[version='>=1.12.3'] -> notebook -> prometheus_client -> twisted -> pyobjc-framework-cfnetwork
  - holoviz -> holoviews[version='>=1.12.3'] -> notebook -> prometheus_client -> twisted -> pyobjc-framework-cocoa
  - holoviz -> holoviews[version='>=1.12.3'] -> notebook -> prometheus_client -> twisted -> pyserial[version='>=3.0']
  - holoviz -> holoviews[version='>=1.12.3'] -> notebook -> prometheus_client -> twisted -> service_identity -> pyasn1-modules
  - holoviz -> holoviews[version='>=1.12.3'] -> notebook -> prometheus_client -> twisted -> soappy -> wstools -> pbr
  - holoviz -> holoviews[version='>=1.12.3'] -> notebook -> prometheus_client -> twisted -> zope.interface[version='>=4.4.2'] -> zope
  - holoviz -> holoviews[version='>=1.12.3'] -> notebook -> send2trash
  - holoviz -> holoviews[version='>=1.12.3'] -> notebook -> terminado[version='>=0.8.1'] -> ptyprocess
  - holoviz -> holoviews[version='>=1.12.3'] -> panel
  - holoviz -> hvplot[version='>=0.4.0']
  - holoviz -> ipywidgets -> widgetsnbextension[version='>=3.4.0,<3.5.0']
  - holoviz -> netcdf4 -> cftime
  - holoviz -> netcdf4 -> hdf5[version='>=1.10.4,<1.10.5.0a0']
  - holoviz -> netcdf4 -> libnetcdf[version='>=4.6.1,<5.0a0'] -> curl -> krb5[version='>=1.16.1,<1.17.0a0'] -> libedit[version='>=3.1.20170329,<3.2.0a0,>=3.1.20170329,<4.0a0']
  - holoviz -> netcdf4 -> libnetcdf[version='>=4.6.1,<5.0a0'] -> curl -> libcurl==7.64.1=h20c2e04_0 -> libssh2[version='>=1.8.2,<2.0a0']
  - holoviz -> netcdf4 -> libnetcdf[version='>=4.6.1,<5.0a0'] -> hdf4[version='>=4.2.13,<4.2.14.0a0'] -> jpeg[version='>=9b,<10a']
  - holoviz -> phantomjs
  - holoviz -> python-snappy -> snappy[version='>=1.1.7,<2.0a0']
  - holoviz -> rise
  - holoviz -> selenium
  - holoviz -> streamz

**Comment by meverson86** [comment]
After doing some digging, I explicitly limited channels and I think I isolated it to a requirement that seems to be specified by the version of numpy bokeh is requiring

conda install --override-channels -c pyviz -c conda-forge holoviz
Collecting package metadata (current_repodata.json): done
Solving environment: failed
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - holoviz -> numpy[version='>=1.16.4'] -> liblapack[version='>=3.8.0,<3.9.0a0'] -> libgfortran-ng[version='>=7,<8.0a0']

**Comment by meverson86** [comment]
I think there is something weird going on with the environment solver, I installed python=3.6 as directed first, but then followed that with installing numpy separate from holoviz, like so:

conda create -n holoviz-tutorial python=3.6
conda activate holoviz-tutorial
conda install --override-channels -c pyviz -c conda-forge numpy=1.16
conda install --override-channels -c pyviz -c conda-forge holoviz

Then conda was able to successfully solve the environment.

**Comment by timsnyder** [comment]
@meverson86 which version of conda were you using?  I just tried your workaround [above](https://github.com/pyviz/holoviz/issues/193#issuecomment-508968059) using conda 4.7.5 and I'm still seeing the PackagesNotFound error in [the previous comment](https://github.com/pyviz/holoviz/issues/193#issuecomment-508967627)

> holoviz -> numpy[version='>=1.16.4'] -> liblapack[version='>=3.8.0,<3.9.0a0'] -> libgfortran-ng[version='>=7,<8.0a0']

Looks like conda installed numpy 1.16.2 when I ran:
>  conda install --override-channels -c pyviz -c conda-forge numpy=1.16

With conda 4.7.5, I'm able to get an environment to solve using either:
> conda create -n holoviz-tutorial -c pyviz -c defaults -c conda-forge  python=3.6 'numpy>=1.16.4' holoviz

or (with conda-forge as higher priority)

> conda create -n holoviz-tutorial -c pyviz -c conda-forge -c defaults python=3.6 'numpy>=1.16.4' holoviz

However, there is definitely something strange going on with conda 4.7.5.  It downloads all of the packages and then complains that the '.conda' new format packages are corrupt. 

I reverted back to conda 4.4.7 (nothing special about the version, it's just what my vm had installed this morning before I took a snapshot) and I was able to get holoviz to install using:

> conda create -n holoviz-tutorial --override-channels -c pyviz -c defaults -c conda-forge  python=3.6  holoviz

Now that I have a working install for tomorrow's tutorial, I'll try go back to looking into what conda 4.7.5 is doing.

**Comment by philippjfr** [comment]
I think there's two fixes here, either downgrading to an earlier conda or installing python=3.7. We'll try to have guidance on this asap.

**Comment by meverson86** [comment]
@timsnyder Could you try using the following command using conda 4.7.5 and see if that works for you?

conda create -n test_env --override-channels -c pyviz -c defaults -c conda-forge python=3.6 holoviz

**Comment by meverson86** [comment]
@philippjfr So I believe the root issue is the phantomjs version in the pyviz channel.

 ◰³ base  ~  conda create -n holoviz_test -c pyviz holoviz=0.1.2             (base) 847ms  Sun 07 Jul 2019 06:27:52 PM EDT
Collecting package metadata (current_repodata.json): done
Solving environment: failed
Collecting package metadata (repodata.json): done
Solving environment: failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

  - bokeh[version='>=1.2.0'] -> pillow[version='>=4.0'] -> freetype[version='>=2.9.1,<3.0a0']
  - datashader[version='>=0.7.0'] -> pillow[version='>=3.1.1'] -> freetype[version='>=2.9.1,<3.0a0']
  - holoviews[version='>=1.12.3'] -> bokeh[version='>=1.1.0,<2.0.0'] -> pillow[version='>=4.0'] -> freetype[version='>=2.9.1,<3.0a0']
  - hvplot[version='>=0.4.0'] -> bokeh[version='>=1.0.0'] -> pillow[version='>=4.0'] -> freetype[version='>=2.9.1,<3.0a0']
  - matplotlib==3.0.3 -> freetype[version='>=2.9.1,<3.0a0']
  - panel[version='>=0.6.0'] -> bokeh[version='>=1.1.0'] -> pillow[version='>=4.0'] -> freetype[version='>=2.9.1,<3.0a0']
  - phantomjs -> fontconfig=2.12 -> freetype[version='>=2.8,<2.9.0a0']
  - scikit-image -> imageio[version='>=2.1.0'] -> pillow -> freetype[version='>=2.9.1,<3.0a0']

looks like the phantomjs 2.1.1 build 0 version in the pyviz channel pins the fontconfig version to 2.12.*, whereas the 2.1.1 build 1 in conda-forge allows it to be any version.  This is why adding the conda-forge channel appeared to fix the issue, and probably didn't pop up for folks if they had conda-forge specified in their .condarc file.

**Comment by jbednar** [comment]
I believe @jlstevens updated the pyviz channel's phantomjs with the one from conda-forge, which should make it work the same with or without that channel.  That doesn't mean it's the right thing to do, as presumably there was a reason it pinned fontconfig before, but at least it gets things working. Please reopen if you have any issues again.
