### ISSUE TITLE
Conda channel nodejs out of date

### ISSUE THREAD

**Issue by zbarry** [holoviz/holoviz#212]
It looks like `nodejs` is present in the pyviz channel (https://anaconda.org/pyviz/nodejs), but its version is 9.11.1. The problem with this is when I go to run `jupyter labextension install @pyviz/jupyterlab_pyviz`, I get this error:

```
error get-caller-file@2.0.5: The engine "node" is incompatible with this module. Expected version "6.* || 8.* || >= 10.*". Got "9.11.1"
error Found incompatible module
```

I guess the nodejs package in the pyviz channel should be updated?

**Comment by jlstevens** [comment]
@zbarry I've gone ahead and removed the nodejs packages from the pyviz channel - the ones available on defaults are more recent and should work. Let us know if there are any problems with this!

**Comment by zbarry** [comment]
Creating an environment as in:

`conda install -c pyviz -c conda-forge -c defaults hvplot jupyterlab nodejs`

or

`conda install -c pyviz -c defaults hvplot jupyterlab nodejs`

now both allow the lab extension build to completion successfully. @jlstevens - what are your thoughts on including `nodejs` as an explicit package dependency? Under the assumption that people will move increasingly to JupyterLab over the old notebook setup, it seems like that might eventually be a good thing to automatically include. I don't know if there are broader consequences of this, though. I only use node indirectly (in cases such as holoviz).

Regardless, problem is solved :+1:

**Comment by jbednar** [comment]
I'll close this for now, but we'll discuss whether to make nodejs a dependency.

**Comment by jlstevens** [comment]
The consensus I've seen that if we decide to include nodejs, it should be part of `pyviz_comms`.
