### ISSUE TITLE
Code formating issue exercises

### ISSUE THREAD

**Issue by ea42gh** [holoviz/holoviz#213]
https://holoviz.org/tutorial/Interlinked_Panels.html The solution to the first exercise appears as follows

![](https://user-images.githubusercontent.com/13033479/62092946-60ead100-b245-11e9-9c1f-2703d3cace2f.png)

**Comment by jsignell** [comment]
Yes this is an issue that I have noticed, but thank you for capturing it! It has to do with sphinx viewing ``` as latex rather code as markdown does. I decided it wasn't super high priority since the solutions look good in both jupyter notebook and jupyterlab, where you have to be to actually be doing exercises.

**Comment by jbednar** [comment]
Still, it makes us look bad, and isn't good for people "playing at" the exercises (imagining it in their mind when skimming the website, then checking if their guess was correct).

**Comment by jsignell** [comment]
I made the fix on nbsite, so should be fixed after a release of nbsite whenever the website is rebuilt.

**Comment by jsignell** [comment]
I'll leave it open until that happens

**Comment by jbednar** [comment]
Thanks!

**Comment by jsignell** [comment]
The site is now rebuilt.
