### ISSUE TITLE
yoffset of label not working?

### ISSUE THREAD

**Issue by an5ir** [holoviz/holoviz#214]
if i do the following:
`hv.Labels({('x', 'y') : [['a',1], ['b',2]], 'text':['a', 'b']}, ['x','y'], 'text')*hv.Scatter([('a',1), ('b', 2)]).opts(padding=0.1)`

it will plot the following:
![image](https://user-images.githubusercontent.com/42062013/62775265-11a36c80-ba9f-11e9-9ab5-bf9c80ec8fb2.png)
but if i try add a yoffset to move the labels above the scatter point:
`hv.Labels({('x', 'y') : [['a',1], ['b',2]], 'text':['a', 'b']}, ['x','y'], 'text').opts(yoffset=0.2)*hv.Scatter([('a',1), ('b', 2)]).opts(padding=0.1)`

 i do not get any output in Jupiter notebook. the following errors in:

![image](https://user-images.githubusercontent.com/42062013/62775393-6ba43200-ba9f-11e9-97c7-27143e87ae4d.png)

is there any way to manipulate the yoffset above the points for categorical plots?

**Comment by philippjfr** [comment]
How come you closed this issue? Did you find a workaround?

**Comment by jbednar** [comment]
It was closed in favor of the one opened on the holoviews repo, which is more appropriate: https://github.com/pyviz/holoviews/issues/3892

**Comment by philippjfr** [comment]
Ah, didn't see that. I was gonna transfer this one, which is an option now.

**Comment by an5ir** [comment]
sorry for the confusion
