### ISSUE TITLE
xarray version incorrect

### ISSUE THREAD

**Issue by fswings** [holoviz/holoviz#215]
I'm trying to replicate (manually) the environment needed for the tutorials and came across this issue.

In the `setup.cfg` and the `environment.yml` file in the repository `xarray=0.12.1A` is specified but doesn't exist either in the pyviz, anaconda or conda-forge channels.

**Comment by jsignell** [comment]
Seems like a typo. I imagine the A shouldn't be there. I'll open a PR. Thanks for catching that!
