### ISSUE TITLE
Unable to access data array inside gv.WMTS tiles

### ISSUE THREAD

**Issue by friedrichknuth** [holoviz/holoviz#219]
@jsignell @ocefpaf

Working from a notebook...

```
import geoviews as gv
import holoviews as hv
hv.extension('bokeh')

lon = -121.8144
lat = 48.7767
dx  = dy = 0.01
url   = 'https://mt1.google.com/vt/lyrs=s&x={X}&y={Y}&z={Z}'

extents = (lon-dx, lat-dy, lon+dx, lat+dy)
tiles = gv.WMTS(url, extents=extents)
tiles
```

I'm trying to get access to the data array and coordinates inside the tiles object so that I can save it to geotif. Not sure if support for this is just built in so my plan was to pull out the data array and save it using rasterio, as suggested here https://github.com/pyviz/geoviews/issues/68.

Not seeing a method that lets me access the array. Maybe there is a hidden one that can be exposed?

**Comment by ocefpaf** [comment]
@jbednar said in pyviz/geoviews#68:

> I'd guess your best bet is to just get the data into a form that rasterio supports, then use rasterio to make the GeoTIFF. 

Indeed. Creating the GeoTIFF in rasterio later is easy. However, it would be nice to be able to access the image from the holo/geo-views object directly. That would make our life easier when exporting it to `rasterio`.

Maybe I did not look into it hard enough but I could not find where the image is stored in the `tile` object for a certain zoom level.

**Comment by ocefpaf** [comment]
As soon as I finished writing this I realized that the interactive backends just read the tiles online, so this is probably not possible unless we use the matplotlib backend to get the array. Maybe `contextily` is a library better suited for this task.

**Comment by jbednar** [comment]
I'm pretty sure that a Bokeh WMTS object never brings the underlying image data into Python at all; the JavaScript object just requests tiles from the webserver as needed and displays them in the browser.  So I don't think there is any straightforward way to export the data; I assume you'd have to write a custom Bokeh extension to read the images and send them to Python for processing.  I bet that would be something people would be interested in, but I don't know of anyone with plans to do that right now.

We do have an example of doing this (http://earthsim.pyviz.org/topics/GrabCut.html), but it uses an external system called [Quest](https://quest.readthedocs.io/en/latest/install.html) to fetch the tiles, paste them together, and select the appropriate region, once we select a region on the visible tiles.

**Comment by ocefpaf** [comment]
> I'm pretty sure that a Bokeh WMTS object never brings the underlying image data into Python at all; the JavaScript object just requests tiles from the webserver as needed and displays them in the browser. 

Yep.

> We do have an example of doing this (http://earthsim.pyviz.org/topics/GrabCut.html), but it uses an external system called Quest to fetch the tiles, paste them together, and select the appropriate region, once we select a region on the visible tiles.

This will probably make our life easier, thanks. For now `contextily` seems to do the job.

**Comment by jbednar** [comment]
Looks like contextily can be used precisely the way we are using Quest.  Since it's relatively simple to do it this way (grab bounding box, request data separately), there probably won't be much enthusiasm for doing the work to do it directly in Bokeh, so I'll close this for now.
