### ISSUE TITLE
Make edited hv.Table values overwrite values in the source dataframe

### ISSUE THREAD

**Issue by hali-geoviz** [holoviz/holoviz#222]
Hi 
I am trying to make efficient use of holoviews to edit some data. I had a look at one example in http://holoviews.org/reference/streams/bokeh/BoundsX.html#bokeh-gallery-boundsx

I did the changes marked in **bold** in order to show all the table rows (commenting the describe()..) for the corresponding points selected and added editable=True in the options builder. What I really want is to be able to edit the table values in the hv.Table and write these edits back to df with edits stored. I would be really interested in this ability to store information back through holoviews.

import pandas as pd
import numpy as np
import holoviews as hv
from holoviews import streams
hv.extension('bokeh')

n=200
xs = np.linspace(0, 1, n)
ys = np.cumsum(np.random.randn(n))
df = pd.DataFrame({'x': xs, 'y': ys})
curve = hv.Curve(df)

def make_from_boundsx(boundsx):
    sub = df.set_index('x').loc[boundsx[0]:boundsx[1]]
    return hv.Table(sub)**.opts(editable=True)  # .describe().reset_index().values, 'stat', 'value')**

dmap = hv.DynamicMap(make_from_boundsx, streams=[streams.BoundsX(source=curve, boundsx=(0,0))])

curve.opts(tools=['xbox_select']) + dmap

**Comment by philippjfr** [comment]
This would break a lot of assumptions in HoloViews, if you need this you can use ``hv.streams.CDSStream`` in HoloViews to get the data or you will be able to use the ``DataFrame`` widget in Panel once it is merged (see https://github.com/pyviz/panel/pull/560).

**Comment by hali-geoviz** [comment]
Sorry, this was not ment as a pull request to change anything in the library. Rather I was interested in examples on how one might approach the type of challenge described. Thank you for the tip on using a CDSStream. I will be happy to see more examples on how to go about changing data through holoviews. I am thinking of things like interactively tagging time series data and write back as an attribute to the input data and simultaneously change coloring of time series plots. I might come back with examples if I manage some of this.

**Comment by philippjfr** [comment]
We should add an example like that to the gallery.
