### ISSUE TITLE
Warnning in the application of pyViz in NS-3

### ISSUE THREAD

**Issue by Pangeensi** [holoviz/holoviz#223]
I used waf command to execute the scripts of NS-3, which were followed "--vis" option. But the performance were  uncompleted with a series of Gtk-WARNING:

(python:2304): Gtk-WARNING **: drawing failure for widget 'GooCanvas': invalid matrix (not invertible)

(python:2304): Gtk-WARNING **: drawing failure for widget 'GtkScrolledWindow': invalid matrix (not invertible)

(python:2304): Gtk-WARNING **: drawing failure for widget 'GtkVBox': invalid matrix (not invertible)

(python:2304): Gtk-WARNING **: drawing failure for widget 'GtkWindow': invalid matrix (not invertible)

**Comment by jbednar** [comment]
Try https://www.nsnam.org ; this is a different project.
