### ISSUE TITLE
Strip references to pyviz off project sites

### ISSUE THREAD

**Issue by jsignell** [holoviz/holoviz#224]
As part of the ongoing rename effort, we need to replace the wording on various project sites to refer to holoviz rather than pyviz:

 - [x] datashader
 - [x] holoviews
 - [x] geoviews
 - [x] hvplot
 - [x] panel
 - [x] colorcet

**Comment by jbednar** [comment]
Does this include renaming sphinx_pyviz_theme to sphinx_holoviz_theme?  I think it ought to, unless it is very painful to do so.

**Comment by jbednar** [comment]
The sites should also each situate the project in the larger holoviz effort, with at least a sentence or two on each site explaining what part of holoviz they are, and linking to both holoviz.org and pyviz.org.

**Comment by jsignell** [comment]
> Does this include renaming sphinx_pyviz_theme to sphinx_holoviz_theme?

I just made a separate issue for that one #225

**Comment by jbednar** [comment]
I think this task is done at the github level, though some packages still need to be released before it takes effect publicly.
