### ISSUE TITLE
Rename github org from pyviz to holoviz

### ISSUE THREAD

**Issue by jsignell** [holoviz/holoviz#227]
I was talking about with matplotlib folks at PyData and they were saying that they'd like for holoviz projects to have their own github org so that the growing number of truly collaborative projects (https://github.com/pyviz/website, https://github.com/pyviz/spec, https://github.com/pyviz/contrib_colormaps) appear more as separate from the holoviz libraries. I took a look at [renaming github orgs](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/renaming-an-organization) and it doesn't seem too hard, so it might be reasonable to rename the pyviz organization to holoviz, and then to quickly move those three repos back to pyviz. That really doesn't seem like it'd be too rough and the links would redirect, so it wouldn't break anyone.

**Comment by jbednar** [comment]
Sounds good to me!  Then there's the question of .pyviz.org and .holoviz.org, and I personally think we should make the same distinction but enforce a single namespace so that X.pyviz.org just forwards to X.Y.org, where Y is holoviz or any other grouping people might need.

**Comment by jsignell** [comment]
That works for me. Are subdomains free on holoviz.org, @jlstevens ?

**Comment by ceball** [comment]
I also agree it's a good idea.

**Comment by jsignell** [comment]
@pyviz/pyviz-dev I am planning to do this tomorrow unless anyone has objections.

**Comment by jbednar** [comment]
Thanks!

**Comment by philippjfr** [comment]
What's the governance model here? If I wanted to move Panel back to PyViz after the move (not saying I will do this), who will have ownership over the org? If someone else wanted their project to the PyViz org what is the approval process?

**Comment by jbednar** [comment]
Previously, I would have said that any Python viz tool could live under the pyviz github org; the more the merrier!  After moving the holoviz tools to their own org, I think the answer is that specific tools like panel should live at a different org, reserving the pyviz github org for repositories that are specifically in support of Python viz in general, not specific projects.  I think the approval process is to raise an issue or make a PR on the pyviz repo and have those who administer the repo (currently consisting of most of the maintainers of Python viz packages) decide whether to merge it.

**Comment by jsignell** [comment]
Do you have a proposal for the governance model? I was planning on giving any viz library author read/write access to the whole pyviz org.

**Comment by jsignell** [comment]
Ok I have now moved all our holoviz repos to holoviz org. I am still working my way through removing references to pyviz, fixing logos, and adding topics pages that point to examples.pyviz.org.
