### ISSUE TITLE
[help wanted]best practice to visualize overlay over remote jupyter notebook

### ISSUE THREAD

**Issue by qianyizhang** [holoviz/holoviz#235]
I have a series of high res images to be visualized (3k x 4k) from a remote server.
Furthermore, I wish to have some interactive overlay (heatmap, detection, etc.) on top of the original images, the overlay data structures are rather sparse compare to original image, and subject to be modified. 

and using gridded data example is seemingly slow. slower than direct display with PIL.Image, and much slower than matplotlib.plot (at smaller figure, which transmit downsampled images I assume)

can someone point me to doc/example/function that may help with my use case?

PS: the ultimate goal is also be able to annotate the image (output the roi coordinates is fine)

**Comment by jbednar** [comment]
It's hard to say much without an example image and some code that you are trying, but I would expect what you are describing to work well if you start a Jupyter or Bokeh server process on the server (not locally), connect to it from your local system, and use `holoviews.operation.datashader.rasterize()` on the image before you overlay or display it. 

BTW, we're working on annotation tools in HoloViews that should make it easy to collect such annotations.  Those should already be available in the latest dev release of HoloViews, but unfortunately we don't yet have a Box annotator for ROIs (for a minor technical reason that we're addressing).

**Comment by qianyizhang** [comment]
thanks alot! I found the rasterize function really helps.
I have another question, how to set the overall figure size? (default is 7x7 i think?)
`
opts.defaults(
    opts.Image(cmap='Gray', fig_size=(12, 12)),
)
`
the above setting seems to set the figure within the canvas, while the overall size is still small as it is.

Also, is there a tutorial for the interactive annotation feature? If not, what functions should I look into

**Comment by qianyizhang** [comment]
I realized they simply using different parameter names
`
opts.defaults( opts.Image(cmap='Gray', height=600, width=400, )
`
works just fine

**Comment by jbednar** [comment]
Ah, right; figsize is for the matplotlib backend, while bokeh uses height and width.
