### ISSUE TITLE
[help wanted] how to created sanky-like hover effect for box/polygons

### ISSUE THREAD

**Issue by qianyizhang** [holoviz/holoviz#240]
I love the hover effect demonstrated in reference/elements/bokeh/Sankey.ipynb, with values in text and ROI shaded. 
Is it possible to make similar effect for box/polygons?
Furthermore, is it possible to have attributes associated to each box/polygons just for hover message visualization?

**Comment by philippjfr** [comment]
Sorry we haven't gotten to this yet. Would you mind moving this question to our [Discourse](http://discourse.holoviz.org/)?
