### ISSUE TITLE
Broken Links on Web Site (Background Page)

### ISSUE THREAD

**Issue by GadgetSteve** [holoviz/holoviz#243]
#### ALL software version info
Web Site as Accessed on 7th of March 2020

#### Description of expected behavior and the observed behavior
Links on https://holoviz.org/background.html in the Demos section expected to work - result in 404 error.

#### Complete, minimal, self-contained example code that reproduces the issue

```
from requests_html import HTMLSession
sess = HTMLSession()
base_url = "https://holoviz.org/background.html"
# Get the response from the base URL
resp = sess.get(base_url)
# Get the links
links = resp.html.links
# At the moment we are only interested in absolute/external links
full_links = [l for l in links if l.startswith('http')]

broken = [] # Storage for broken links
for l in full_links: # Check each in turn
    print(f"Checking {l}")
    try:
        link_resp = sess.get(l)
    except Exception as e: # Very bad Links
        print(f"Failed to get {l} - {e}")
        broken.append(l)
    if not link_resp.ok or link_resp.status_code != 200:  # i.e Bad Lnks
        broken.append(l)
print('Broken:', broken)
```
Output:
Checking http://datashader.org/topics/landsat.html
Checking http://pandas.pydata.org
Checking https://anaconda.org/jbednar/nyc_taxi
Checking https://anaconda.org/jbednar/opensky
Checking http://scitools.org.uk/cartopy
Checking http://holoviews.org/gallery/apps/bokeh/game_of_life.html
Checking http://bokeh.pydata.org
Checking http://holoviews.org/gallery/demos/bokeh/dragon_curve.html
Checking http://panel.pyviz.org
Checking http://holoviews.org/reference/apps/bokeh/selection_stream.html
Checking https://fastparquet.readthedocs.io
Checking http://holoviews.org
Checking http://geo.holoviews.org
Checking http://numba.pydata.org
Checking http://holoviews.org/reference/streams/bokeh/BoundsX.html
Checking http://hvplot.pyviz.org
Checking http://dask.pydata.org
Checking http://xarray
Failed to get http://xarray - HTTPConnectionPool(host='xarray', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F3076FB040>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Checking http://param.pyviz.org
Checking http://jupyter.org
Checking http://datashader.org
Checking https://panel.pyviz.org/user_guide/Interact.html
Checking http://holoviews.org/gallery/apps/bokeh/crossfilter.html
Checking http://holoviews.org/reference/containers/bokeh/DynamicMap.html
Checking http://holoviews.org/gallery/apps/bokeh/mandelbrot.html
Checking https://anaconda.org/jbednar/edge_bundling
Broken: ['http://xarray', 'http://datashader.org/topics/landsat.html', 'http://datashader.org/topics/landsat.html']

#### Stack traceback and/or browser JavaScript console output
Link to Land Sat example goes to http://datashader.org/topics/landsat.html should go to https://examples.pyviz.org/landsat/landsat.html instead.

#### Screenshots or screencasts of the bug in action
N/A

**Comment by jbednar** [comment]
Thanks! These were already fixed in master, but not yet on the released website.  I may have just forgotten to start the website build, but there may have been some problem building it when I last tried. I've started it building again; we'll see! In any case, thanks for the reminder.

**Comment by GadgetSteve** [comment]
The published website still has incorrect links to 'http://xarray' & 'http://datashader.org/topics/landsat.html'

**Comment by jbednar** [comment]
Yep.  Looks like this site isn't set up to build on commit messages like our others are; instead it needs  `git tag -d website ; git tag -a -m "Build website" website ; git push -f origin website`.  I just tried that, but the build is failing for a reason I don't recognize:https://travis-ci.org/holoviz/holoviz/builds/659800781

We'll have to debug that...

**Comment by jbednar** [comment]
Ok, looks like Travis updated their build images, and after updating our pythons to match, the website build finally succeeded.  Should be live now at http://holoviz.org/background.html. Thanks for watching out for us, and _now_ if you see any other problems they will be things that still need fixing.

**Comment by GadgetSteve** [comment]
All looking good James (@jbednar ) - if I spot any other issues I will raise a fresh ticket (and PR if possible).

**Comment by jbednar** [comment]
Thanks!
