### ISSUE TITLE
Bump Datashader to 0.11

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/holoviz#251]
I'm running `conda update -c pyviz holoviz`. I can see that DataShader 0.10 is installed. But I know 0.11 is out.

Should this not be updated?

**Comment by philippjfr** [comment]
Eventually yes, but the HoloViz metapackage should generally be pinned strictly to avoid any issues (as you've been finding today). We no longer recommend the metapackage for anything except the tutorial.

**Comment by jbednar** [comment]
Fixed in #264.
