### ISSUE TITLE
pn.interact not stretching

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/holoviz#254]
Holoviz 0.11.3

#### My Pain

I would like to show to fellow Pythonistas how awesome Holoviz and Panel is. But this example does not look nice

02_Building_Panels.ipynb

![image](https://user-images.githubusercontent.com/42288570/83386920-1fd6c680-a3ec-11ea-9ac1-7e5a2fe27841.png)

#### Workaround

`pn.config.sizing_mode="stretch_width"`

![image](https://user-images.githubusercontent.com/42288570/83387056-5f051780-a3ec-11ea-8774-949d4848583e.png)

```python
pn.config.sizing_mode="stretch_width"

def select_row(row=0):
    return df.loc[row].compute()

pn.interact(select_row, row=(0, len(df)-1), width=10)
```

**Comment by jbednar** [comment]
Right. The example worked well when it was written, but at some point the datetime representation (from Pandas?) changed to include a very long string of characters that don't fit into the space allotted for them.  It's possible to change the sizing mode as you show here, but instead I've fixed this in #261 by changing the datetime formatting back to something more reasonable.
