### ISSUE TITLE
Add plotly to pandas plot api backends

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/holoviz#255]
You can now use plotly as a plotting backend for pandas.

See https://plotly.com/python/pandas-backend/

I think it should be added to the list in `04_Basic_Plotting.ipynb`.

![image](https://user-images.githubusercontent.com/42288570/83394011-194e4c00-a3f8-11ea-966b-7365b0215d54.png)

**Comment by jbednar** [comment]
Thanks; fixed in #261.
