### ISSUE TITLE
In 05_Composing_Plots the rasterized_pop plot is empty

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/holoviz#258]
HoloViz: 0.11.3

05_Composing_Plots

![image](https://user-images.githubusercontent.com/42288570/83402464-13ac3280-a407-11ea-9c02-1e1cf3e6fd32.png)

**Comment by MarcSkovMadsen** [comment]
#### Additional Context

If I remove `.opts(logz=True)` the map actually shows.

![image](https://user-images.githubusercontent.com/42288570/83402804-bd8bbf00-a407-11ea-8f9d-1bd7f235566e.png)

I also needed to remove the `.opts` below.

![image](https://user-images.githubusercontent.com/42288570/83403075-41de4200-a408-11ea-8e0d-e6b98dc45bcc.png)

**Comment by MarcSkovMadsen** [comment]
### Subjective Comment

I think the data and intentions of the example is great. But the end result does not at all emphasize this.

I would have a hard time selling this to anybody. It's really difficult to see the correlation between the areas with the high population density and the earth quakes. And personally I think the map color is not very pretty.

Sorry. and thanks for all the effort that has gone into producing this example.

**Comment by MarcSkovMadsen** [comment]
Its the same problem in Exercise 3

![image](https://user-images.githubusercontent.com/42288570/83404309-ba460280-a40a-11ea-9887-ec5b8630ede9.png)

**Comment by philippjfr** [comment]
Duplicate of https://github.com/holoviz/holoviews/issues/4376. I'll try to update the notebook today.

**Comment by jbednar** [comment]
Fixed in #264.
