### ISSUE TITLE
Do we still use or advertise examples/environment.yml?

### ISSUE THREAD

**Issue by ceball** [holoviz/holoviz#267]
Seems not used and out of date, and the docs say to install a holoviz package (into a dedicated env). So shall we remove examples/environment.yml?

**Comment by jbednar** [comment]
Yes. We were just wondering (a) where that came from (as it indicates that it's auto-generated), and (b) what it was meant to be for. We're pretty sure it can be deleted, but as discussed https://github.com/holoviz/holoviz/issues/110#issuecomment-637775884 may soon move to an entirely different approach, so we left it as-is for now.

**Comment by ceball** [comment]
(a) It's generated from setup.cfg, but by a human using pyctdev (not automatically/on CI).
(b) Early on, I believe we suggested people get set up for tutorials by getting the examples dir and then creating an env. That would have been quite a long ago now, though.

**Comment by ceball** [comment]
I see in the thread you linked to that my 2018 comment predicts the name holoviz 😂

**Comment by jbednar** [comment]
Yeah; having open and still-relevant issues talk about pyviz was confusing, and re-opening all the issues as new ones saying holoviz would hide who said what, so, revisionist history it is!

**Comment by jbednar** [comment]
Anyway, thanks for deleting it in #266.
