### ISSUE TITLE
Tutorial refers to notebook "Exploration with containers" that doesn't exist

### ISSUE THREAD

**Issue by Dr-Irv** [holoviz/holoviz#27]
I'm going through the tutorial, which is very well done.  Kudos!

In notebooks ``03_Customizing_Visual_Appearance.ipynb`` and ``08_Custom_Interactivity.ipynb`` there are references to the notebook "exploring with containers" ``04-exploration-with-containers.ipynb`` .  But that notebook doesn't exist.

A related issue, which is more pedagogical, is that in the notebook ``08_Custom_Interactivity.ipynb``, there is the statement:

> In the exploring with containers section, the DynamicMap container was introduced. In that section, the arguments to the callable returning elements were supplied by HoloViews sliders

The issue is that the DynamicMap container really hasn't been introduced in any prior notebooks (beyond an example in notebook 1), making notebook 8 a little harder to understand.

Hope this helps improve the tutorial.

**Comment by jlstevens** [comment]
Thanks for the feedback!

I agree with both points, we need to fix any broken references and that misleading statement was probably from a time when the material was ordered differently and now needs updating...
