### ISSUE TITLE
Deploying Bokeh Apps Link is broken.

### ISSUE THREAD

**Issue by earik87** [holoviz/holoviz#273]
In this page; https://holoviz.org/talks/index.html, the link to Deploying Bokeh Apps Tutorial is broken. 

https://holoviz.org/tutorial/13_Deploying_Bokeh_Apps.html

![image](https://user-images.githubusercontent.com/36437947/89993910-aed34b00-dc87-11ea-86f7-095b44805f9b.png)

**Comment by jbednar** [comment]
Thanks for the report!
