### ISSUE TITLE
Link to www.holoviz.org in the About section not working.

### ISSUE THREAD

**Issue by willirath** [holoviz/holoviz#277]
The description of this project links to www.holoviz.org which cannot be resolved (at least from the WiFi I'm in currently). Dropping the subdomain `www.` seems to fix this.

**Comment by jbednar** [comment]
Thanks! Can you give a URL for the page where you found this problem?  I don't see such a link at view-source:http://holoviz.org/about.html or https://raw.githubusercontent.com/holoviz/holoviz/master/README.md or anywhere in the repo right now.

**Comment by willirath** [comment]
Github entry page: 

<img width="1239" alt="holoviz_link_broken" src="https://user-images.githubusercontent.com/5700886/96593083-6a98a280-12e9-11eb-9427-3a9a6874a36f.png">

**Comment by jbednar** [comment]
Ah, thanks!
