### ISSUE TITLE
Dynamically sort Pandas dataframe columns 

### ISSUE THREAD

**Issue by anuraghuram** [holoviz/holoviz#279]
Is there an option to dynamically filter columns similar to Dash? (see here for usage: https://dash.plotly.com/datatable/interactivity)

**Comment by ppwadhwa** [comment]
This sounds like a question that is about panel.  Panel recently added a tabulator object that does allow dynamic sorting.  

https://pyviz-dev.github.io/panel/reference/widgets/Tabulator.html
