### ISSUE TITLE
Clarify rasterize vs datashade in tutorial

### ISSUE THREAD

**Issue by ablythed** [holoviz/holoviz#286]
Currently in Tutorial 6 (Large Data), both `rasterize()` and `datashade()` are used and it isn't totally clear when users should choose one of those operations over the other. `datashade()` is introduced formally there, but `rasterize()` is only used, not explained. This question is answered in more detail in the [User Guide](http://holoviews.org/user_guide/Large_Data.html), which is linked at the bottom of the tutorial page, but it still might be helpful to include a brief explanation of the difference in Tutorial 6. #275 suggests replacing `datashade()` with `rasterize()` everywhere in the examples, but I'm not sure if that's relevant here or not.

**Comment by jbednar** [comment]
I agree. Let's just delete tutorial 6; I think Datashader is now covered in 02, and we don't need this extra duplicative stuff.  There's a bit new there, but probably nothing anyone can really grok in the time available, and yet not enough to compare with the hv Large Data guide or datashader.org.

**Comment by jbednar** [comment]
In any case, 02 now only covers rasterize, not datashade, and that's what most people will ever need nowadays.
