### ISSUE TITLE
holoviz package outdated

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/holoviz#296]
A user reports that he gets a lot of errors from “pip install --user holoviz”. See https://discourse.holoviz.org/t/is-there-no-holoviz-installation-via-pip/2681

When I inspect pypi it looks like latest release is 0.11.6 published more than a year ago. 

![image](https://user-images.githubusercontent.com/42288570/129760353-5f79ac8c-567d-4308-ad8d-95045eb58e27.png)

A version 0.12.0 was published 28 days ago but is categorized as "dev". (@jlstevens ).

![image](https://user-images.githubusercontent.com/42288570/129760420-0a665738-bf68-4440-aa1b-ea68c6d7c41d.png)

When I inspect conda I see version 0.11.6 released more than a year ago.

![image](https://user-images.githubusercontent.com/42288570/129760635-0dffcdb8-59cc-4242-b86f-908689c3b096.png)

## Solution 

Get packages updated or remove them every where if there is not resources to keep them updated. They give a wrong impression to potential users.

**Comment by jlstevens** [comment]
I think this issue can be closed now. The solution we opted for is now implemented:

* The old holoviz packages have been yanked from PyPI
* New conda packages have been uploaded where the dependencies are unpinned:

![image](https://user-images.githubusercontent.com/890576/134179715-e8ae0e33-9f1d-4152-b6a9-f608c6a58696.png)

Happy to reopen if more discussion is required.

**Comment by FlorinAndrei** [comment]
@jlstevens - Does that mean that, going forward, the official installation method is based on Anaconda? No pip?

**Comment by jlstevens** [comment]
After yanking you can still `pip install` if you specify the exact version. 

That said, we are discouraging the use of the metapackage in general: for anyone who still wish to use it, we would encourage using `conda` over `pip`.

**Comment by FlorinAndrei** [comment]
@jlstevens Can something be done about this page, please? https://holoviz.org/installation.html

It's not the installation of Holoviz, it's the installation of some tutorial. Those instructions should be moved to the Tutorial page.

The Installation page should describe just how to install Holoviz - be that via conda, conda + pip, or something else.

As a complete beginner to Holoviz, that page was very confusing. What I was looking for was just a clean install of Holoviz. The tutorial installation should be a separate process.

**Comment by jlstevens** [comment]
That is a very good point. What would you recommend @jbednar ?

**Comment by jbednar** [comment]
Good point. Installing the tutorial _is_ the way that we would recommend that most people get started. But then once they've gone through the tutorial, I'd recommend they do a minimal install of just the packages they need in their own environment. So I think we should add an introductory paragraph to that page, then a final step 6 explaining what to do after you are happy with the tutorial and are ready to work on your own projects.

**Comment by FlorinAndrei** [comment]
To be completely honest, and to give you the perspective of someone new to Holoviz:

I've found Holoviz via an article in Towards Data Science. The author mentioned how she couldn't figure out why Holoviz, while being such an excellent collection of packages, has so few users.

Me trying to figure out how to do a clean install of Holoviz: I think I know why.
