### ISSUE TITLE
HoloViz Discourse need critical update

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/holoviz#298]
https://discourse.holoviz.org/admin

![image](https://user-images.githubusercontent.com/42288570/130729212-86564a6d-100b-40dc-b97c-f667cb69de85.png)

**Comment by philippjfr** [comment]
It pretty much always does. Critical updates come out about once a week it seems.

**Comment by philippjfr** [comment]
Updated.

**Comment by MarcSkovMadsen** [comment]
Thanks. I did not know.
