### ISSUE TITLE
Conda installation missing pandas provider

### ISSUE THREAD

**Issue by douglasmacdonald** [holoviz/holoviz#300]
With a clean conda env I was unable install Holoviz.

#### version info

https://anaconda.org/pyviz/holoviz 0.13.0

#### Description of expected behavior and the observed behavior

It complained that `pandas` was not there.

#### Complete, minimal, self-contained example code that reproduces the issue

```
conda install -y -c pyviz holoviz
```

#### Stack traceback

`Problem: package holoviz-0.11.6-py_0 requires pandas 1.0.3, but none of the providers can be installed`

**Comment by jbednar** [comment]
We'd no longer recommend using the `holoviz` conda package for installation; instead please follow the installation instructions at https://holoviz.org/installation.html#installation .
