### ISSUE TITLE
Mercury download numbers incorrect.

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/holoviz#324]
I believe mercury package on pyviz.org all tools have too low Download Numbers. My guess is the Numbers are for the Mercury package and not the mljar-Mercury package.

I am on mobile phone and cannot investigate if this is true cause.

**Comment by droumis** [comment]
looks like I can't transfer this to [pyviz.org repo](https://github.com/pyviz/pyviz.org) maybe because it's a different owner/org. @MarcSkovMadsen want to close this and open a new issue there?
