### ISSUE TITLE
Rename `master` branch to `main`?

### ISSUE THREAD

**Issue by pavithraes** [holoviz/holoviz#339]
I was in the Holoviz sprint at PyData Global, and noticed the primary branch is `master` across all holoviz projects. Would the team consider moving to `main` to be more inclusive?

Useful reference: https://github.com/github/renaming

**Comment by maximlt** [comment]
Oh I definitely want to do that. It's just that I'd like it to happen all as once, and this change has to be made over about 20+ repositories across multiple organizations.

**Comment by maximlt** [comment]
Fixed by https://github.com/holoviz/holoviz/pull/345 and similar PRs across all projects.
