### ISSUE TITLE
jinja needs to be updated to at least version 3.0.0 in Tutorial

### ISSUE THREAD

**Issue by gregorywaynepower** [holoviz/holoviz#341]
Hey Everyone,

I wanted to let y'all know that the [Final Dashboard section](https://holoviz.org/tutorial/Dashboards.html#final-dashboard) is throwing the following warning:

`ImportError: Pandas requires version '3.0.0' or newer of 'jinja2' (version '2.11.3' currently installed).`

**Comment by maximlt** [comment]
Hi @gregorywaynepower !

Thanks for reporting that, we'll fix that.

cc @droumis : another reason to re-lock the project 🙃

**Comment by droumis** [comment]
fixed in #335
