### ISSUE TITLE
Upload new anaconda-project example

### ISSUE THREAD

**Issue by hoxbro** [holoviz/holoviz#349]
With the change to main, new users cannot run the holoviz examples. See https://discourse.holoviz.org/t/issue-installing-holoviz-tutorial/4792.

We should upload an updated `anaconda-project` with the new URL.  

Also observed these warnings:

``` python
Potential issues with this project:

  * anaconda-project-lock.yml: Env spec 'default' has changed since the lock file was last updated (env spec hash has changed from bb0eadf4beaa2b22c7b841150d8e4cb42618999c to e33aab18f46fa82d4d02e9a9261f18cae61b7c7e)

  * anaconda-project-lock.yml: Env spec 'test' has changed since the lock file was last updated (env spec hash has changed from 61ef260560c348328aca81ca22579a3fc3d252ca to 52a32be29aa26d9ad706f8a767d259ef57832612)

  * anaconda-project-lock.yml: Env spec 'doc' has changed since the lock file was last updated (env spec hash has changed from 44164ece41b46e883e7c4c8650493d42d1c91b94 to 15ac1824f1596e87bb1795031cfd9495f24cf89a)
```

**Comment by jbednar** [comment]
Thanks; please do!

**Comment by maximlt** [comment]
I don't get the issue in the post on Discourse. Old links to *master* should redirect to *main*: https://raw.githubusercontent.com/holoviz/holoviz/master/examples/assets/usgs_logo.png. Where does it fail exactly?

**Comment by hoxbro** [comment]
It works fine when clicking on the link, but when using `anaconda-project` it does not redirect. 

> Thanks; please do!

Will love to do it, but don't know how to do it.

**Comment by maximlt** [comment]
> It works fine when clicking on the link, but when using anaconda-project it does not redirect.

Oh :( That must have broken other things then.

> Also observed these warnings:

Did you get them running `anaconda-project` from the downloaded tutorial?

> Will love to do it, but don't know how to do it.

I'll check if I have notes on how to do that!

**Comment by maximlt** [comment]
This problem came up as the link referenced in the `downloads` section of the project seems to be the old way Github was offering to reference "raw" data. Redirects don't work for them unfortunately.

https://github.com/holoviz/holoviz/blob/9d01197813d51379b831409477d214128a9b7a76/examples/anaconda-project.yml#L88-L91

Newer links look like this and redirects work for them:

```
https://raw.githubusercontent.com/holoviz/holoviz/master/examples/assets/usgs_logo.png
https://raw.githubusercontent.com/holoviz/holoviz/main/examples/assets/usgs_logo.png
```

**Comment by maximlt** [comment]
Link updated in https://github.com/holoviz/holoviz/pull/354

**Comment by maximlt** [comment]
Fixed by uploading a new tutorial to holoviz.org that matches with `v0.16.1`.
