### ISSUE TITLE
SciPy 23 tutorial updates

### ISSUE THREAD

**Issue by jbednar** [holoviz/holoviz#364]
In advance of the SciPy 2023 tutorial in July, I've reviewed the tutorial at holoviz.org. It looked like a good introduction overall, but if anyone has proposals for wholesale changes, go for it! In the meantime, I have some suggestions and to-do items for updating the current content:

- [Setup](https://holoviz.org/tutorial/Setup.html)
  - [x] Needs versions updated to Panel 1.x, etc. (@Hoxbro, aim for Panel 1.2)
     - Hoxbro: Pinned to 1.2 
  - [x] Needs checking updated to look for current versions (@Hoxbro)

- [Overview](https://holoviz.org/tutorial/Overview.html)
  - [ ] Should move Lumen to the end of the logo bar (@jbednar )

- [Plotting](https://holoviz.org/tutorial/Plotting.html)
  - [x] Datashader plot should not show negative values in the color bar (should already be fixed in Bokeh 3) (@maximlt) => maximlt: Indeed negative values are no longer shown!

<img width="1066" alt="image" src="https://github.com/holoviz/holoviz/assets/35924738/3031eb98-dc82-4dd0-b1ca-9a8dd0f537bb">

  - [x] show hvplot Explorer (@maximlt)

- [Composing Plots](https://holoviz.org/tutorial/Composing_Plots.html)
  - [x] Maybe point ahead to Panel to mention that arbitrary layouts are easy in Panel? (@jlstevens) (https://github.com/holoviz/holoviz/pull/372)
  - [ ] Show Panel's new swiping functionality to compare two plots (@Hoxbro)

- [Interlinked Plots](https://holoviz.org/tutorial/Interlinked_Plots.html)
  - [x] Before showing link_selections, maybe just show axis linking and how to disable it? (@Hoxbro)
     - hoxbro: I have added this to the previous notebook. 

- [Interactive Pipelines](https://holoviz.org/tutorial/Interactive_Pipelines.html)
  - [x] Rewrite descriptions to explain that hvPlot .interactive is an easy way to get reactive objects driven by widgets, and that Panel offers lots of other ways to get such objects too (@maximlt)
  - [x] Can we easily avoid the flicker at this stage nowadays? (@maximlt )
  - [ ] "link_selections does not currently understand Interactive objects" -- can this be fixed, both for Interactive and also maybe for pn.bind closures? (https://github.com/holoviz/holoviews/issues/5765) (@philippjfr , but unlikely to be before SciPy)

- [Dashboards](https://holoviz.org/tutorial/Dashboards.html)
  - [ ] Rename to apps? => Simon (0), Maxime (-1), Jean-Luc (-1)
  - [ ] Add publishing to Anaconda Notebooks and/or Pyodide? => Add simple sentence (@maximlt); set up for the tutorial (@sophiamyang )
  - [x] Mention Lumen (@maximlt)

- [Custom Interactivity](https://holoviz.org/tutorial/Custom_Interactivity.html)
  - [ ] Sure would be nice to have a higher-level way to set up simple drilldown like this (surely there is an issue for this already, but I can't find one) (@jbednar )

- [Custom Dashboards](https://holoviz.org/tutorial/Custom_Dashboards.html)
  - [ ] Do we still need .watch here? Is that something we want to advertise like this? (@philippjfr )

- [Advanced Dashboards](https://holoviz.org/tutorial/Advanced_Dashboards.html)
  - [ ] Needs to have the APIs used reviewed to see if they are the ones we currently recommend (@philippjfr )

Also see https://github.com/holoviz/holoviz/issues/337, https://github.com/holoviz/holoviz/issues/328, https://github.com/holoviz/holoviz/issues/320, https://github.com/holoviz/holoviz/issues/317, https://github.com/holoviz/holoviz/issues/278, https://github.com/holoviz/holoviz/issues/275

It would be nice to rebuild the website with pyodide-based interactivity and/or provide JupyterLite-executable versions of the notebooks, though some use Datashader and thus won't currently work with such browser-based Python approaches.

**Comment by maximlt** [comment]
> Can we easily avoid the flicker at this stage nowadays? (@maximlt )

@jbednar do you mean the flicker when the Matplotlib plot is re-rendered on this line?

> dfi[dfi['mag'] > mag_slider].plot(y='depth', kind='hist', bins=np.linspace(0, 50, 51))

(My answer at this stage would be, I don't know 🙃 )

**Comment by jbednar** [comment]
@maximlt , the flicker comment is about:

<img width="916" alt="image" src="https://github.com/holoviz/holoviz/assets/1695496/2e0cab98-eba9-4781-85f8-ec8a7ebf2681">

**Comment by hoxbro** [comment]
> Show Panel's new swiping functionality to compare two plots

This notebook does not use Panel. My opinion is also that it does not belong in this notebook, as it has nothing to do with HoloViews. 

> It would be nice to rebuild the website with pyodide-based interactivity and/or provide JupyterLite-executable versions

I think we should do it, but I don't think it should be because of Scipy 2023. A conference with non-optimal internet will give an unnecessary bad experience. 

If I were presenting, I would reduce the way people can run the tutorial, not expand it. I would be scared that if something is not working in, e.g., the Jupyterlite environment, there is no way for me to fix it. Whereas, I know how a conda environment works and will be able to give some guidance.

**Comment by droumis** [comment]
I migrated unfinished tasks to a new issue so we can start preparing for next year - https://github.com/holoviz/holoviz/issues/376
