### ISSUE TITLE
HoloViz tutorial enhancements for SciPy 2024

### ISSUE THREAD

**Issue by droumis** [holoviz/holoviz#376]
In preparation for SciPy 2024, let's collect tasks that we need to complete well in advance. Please add to the list

## Tutorial pages
- [Setup](https://holoviz.org/tutorial/Setup.html)
- [x] Move the tutorial instructions to the Setup page (https://github.com/holoviz/holoviz/issues/317) @maximlt  

- [Overview](https://holoviz.org/tutorial/Overview.html)
  - [ ] Should move Lumen to the end of the logo bar (@jbednar )

- [Plotting](https://holoviz.org/tutorial/Plotting.html)

- [Composing Plots](https://holoviz.org/tutorial/Composing_Plots.html)
  - [ ] Show Panel's new swiping functionality to compare two plots (@Hoxbro)

- [Interlinked Plots](https://holoviz.org/tutorial/Interlinked_Plots.html)

- [Interactive Pipelines](https://holoviz.org/tutorial/Interactive_Pipelines.html)
  - [ ] "link_selections does not currently understand Interactive objects" -- can this be fixed, both for Interactive and also maybe for pn.bind closures? (https://github.com/holoviz/holoviews/issues/5765) (@philippjfr , but unlikely to be before SciPy)

- [Dashboards](https://holoviz.org/tutorial/Dashboards.html)
  - [ ] Rename to apps? => Simon (0), Maxime (-1), Jean-Luc (-1)
  - [x] Add publishing to Anaconda Notebooks and/or Pyodide? => Add simple sentence (@maximlt); set up for the tutorial (@sophiamyang )

- [Custom Interactivity](https://holoviz.org/tutorial/Custom_Interactivity.html)
  - [ ] Sure would be nice to have a higher-level way to set up simple drilldown like this (surely there is an issue for this already, but I can't find one) (@jbednar )

- [Custom Dashboards](https://holoviz.org/tutorial/Custom_Dashboards.html)
  - [ ] Do we still need .watch here? Is that something we want to advertise like this? (@philippjfr )

- [Advanced Dashboards](https://holoviz.org/tutorial/Advanced_Dashboards.html)
  - [ ] Needs to have the APIs used reviewed to see if they are the ones we currently recommend (@philippjfr )

## Other
- Platforms to consider building on
  - GitHub codespaces (Bokeh is considering it https://github.com/bokeh/tutorial/issues/19)
  - Anaconda Notebooks

- Additional issues relating to the tutorial experience:
  -  https://github.com/holoviz/holoviz/issues/337
  -  https://github.com/holoviz/holoviz/issues/328
  -  https://github.com/holoviz/holoviz/issues/320
  -  https://github.com/holoviz/holoviz/issues/278
  -  https://github.com/holoviz/holoviz/issues/275
  - It would be nice to rebuild the website with pyodide-based interactivity and/or provide JupyterLite-executable versions of the notebooks, though some use Datashader and thus won't currently work with such browser-based Python approaches.

- Comments/Lessons from SciPy 2023 to keep in mind:
  - Most popular question was “is there a way to install it without using conda?”
  - We need to test it works on Windows (people who have ended up watching the tutorial rather then running it are using Windows)
  - We need to test running it in nebari.
  - color bar disappear when define cmap
  - people ask does panel reply on Tornado? And why does it use Tornado?
  - people noticed the runnable Python code in docs and they like it and would like use it on their own website

**Comment by ahuang11** [comment]
Link selections with bar charts seem broken:
```python
import numpy as np
import pandas as pd
import holoviews as hv

from holoviews.util.transform import dim
from holoviews.selection import link_selections
from holoviews.operation import gridmatrix
from holoviews.operation.element import histogram
from holoviews import opts
from bokeh.sampledata.autompg import autompg
autompg

hv.extension('bokeh', 'plotly', width=100)

autompg_ds = hv.Dataset(autompg, ['yr', 'name', 'origin'])

mopts = opts.Points(size=2, tools=['box_select','lasso_select'], active_tools=['box_select'])
w_accel_scatter = hv.Scatter(autompg_ds, 'weight', 'accel')
mpg_hist = histogram(autompg_ds, dimension='mpg', normed=False).opts(color="green")
violin = hv.Violin(autompg_ds, [], 'hp')

mpg_ls = link_selections.instance()
mpg_ls(w_accel_scatter + mpg_hist + violin)
```

https://github.com/holoviz/holoviz/assets/15331990/3aaa03a3-3910-4867-9d47-2465ece13253

**Comment by jbednar** [comment]
@ahuang11 , can you move that to an issue on HoloViews and link it from here?

**Comment by ahuang11** [comment]
Done: https://github.com/holoviz/holoviews/issues/6248
