### ISSUE TITLE
Bokeh & Jupyter Blurriness on Chrome

### ISSUE THREAD

**Issue by mg3146** [holoviz/holoviz#397]
Hi, I wasnt 100% sure where to post this bug. Maybe its a Jupyter thing, a bokeh thing or a holoviz thing, but my team have noticed that bokeh plots are rendering slightly blurry / fuzzy in certain cases.  It seems to occur when using chrome & jupyter, but its hard to isolate.  Here are some examples, [using the hvplot docs](https://hvplot.holoviz.org/user_guide/Plotting.html)!

**Microsoft Edge:** (you may have to click image to see it properly)
![image](https://github.com/holoviz/holoviz/assets/8430756/bcd61614-e1b3-4158-b78d-4825af9814d2)

**Chrome:** (you may have to click image to see it properly)
![image](https://github.com/holoviz/holoviz/assets/8430756/41e1ee9c-ca83-4c1b-9109-6758c627c3b8)

For comparison, here is what the (I assume) non-jupyter-generated-website output looks like.  From [the bokeh docs](https://docs.bokeh.org/en/latest/docs/examples/basic/annotations/legend.html):

**Edge:** (you may have to click image to see it properly)
![image](https://github.com/holoviz/holoviz/assets/8430756/34a9eaff-de95-4a2a-9739-724a9ac18d0a)

**Chrome** (you may have to click image to see it properly)
![image](https://github.com/holoviz/holoviz/assets/8430756/da058259-02fc-428d-b94b-da426495e087)

Thanks!

**Comment by droumis** [comment]
Thanks for reporting. We definitely want our docs and plots nice and sharp. However, this is very unlikely to be HoloViz thing and I don't think there is much we can do. If you post this observation in stackoverflow and maybe even the [HoloViz Discourse](https://discourse.holoviz.org/), perhaps someone in the community has run into this and has a suggested solution. My best guess is that it's related to chrome or chrome extension version/settings. For me (chrome, mac osx), the hvPlot site looks crisp and equal in resolution to Bokeh's docs.

<img width="1034" alt="image" src="https://github.com/holoviz/holoviz/assets/6613202/f19032d7-22a7-455e-9ad2-805ef75e04ff">
