### ISSUE TITLE
Reorganize primary navigation

### ISSUE THREAD

**Issue by droumis** [holoviz/holoviz#398]
extracted from #351

## Reorganize primary navigation
- [x] Remove 'Introduction'; users can get to the homepage by clicking on the holoviz logo 
- [x] Merge 'Installation' content into the Tutorial 'setup' https://github.com/holoviz/holoviz/pull/400
- [ ] Move 'Talks, 'Background', 'Tutorial', 'FAQ, into a new 'Learn' page. The current Talk page should become just one of several listed talks.
- [ ] ~~Move 'Roadmap' as a subpage of 'Contribute'~~
- [x] Rename 'Topics' as ~~'Topic Gallery'~~ as 'Examples'
- [ ] Create a new 'Start Here' page for new content on choosing the appropriate HoloViz tools
- [x] Create a new 'Blog' link
- [ ] Contingent on being able to customize the 'More' word dropdown... Replace the 'More' Dropdown with something like 'About', and nest new pages such as 'Governance', 'HEPs', 'Roadmap'. If we cannot customize 'More', nest these new pages into 'About'. Either way, ensure things work as expected on mobile.
- [ ] Order the revised main nav as follows: Start Here, Learn, Examples, Community, Contribute, Blog, About

Nav proposal: 

- Start Here (WIP)
- Learn
    - Background 
    - Talks
    - Tutorial
- Examples (link to examples site)
- Community
- Contribute
- Blog (link to blog site)
- About
    - Governance
    - HEPs
    - Roadmap

**Comment by maximlt** [comment]
>  Rename 'Topics' as ~~'Topic Gallery'~~ as ~~'Examples'~~ Gallery

I think I'd prefer `Examples` since it's the domain name of `examples.holoviz.org`.

**Comment by maximlt** [comment]
I just thought we might want to expose the code of conduct on the website too.

**Comment by maximlt** [comment]
Had another idea, I think it'd be nice to include a dropdown in the navbar with links to all the holoviz projects (panel, holoviews, hvplot, etc.). If we do that, it means we have 8 top-level entries in the navbar which is maybe too much (maybe we could nest `Contribute` under `Community`).

**Comment by ahuang11** [comment]
Should HEPs be under Contribute? Thus far, they only concern maintainers/contributors. And should the search instead use the full name (HoloViz Enhancement Proposal (HEP)?

**Comment by maximlt** [comment]
On python.org the PEP link is under `Documentation`, that's also an alternative, i.e. renaming `Learn` as `Documentation` and having `HEP` there.
<img width="1266" alt="image" src="https://github.com/user-attachments/assets/11ab4c0c-5a13-4288-a9c0-91c5e2ff47b9">
