### ISSUE TITLE
Holoviz tutorial project not found in anaconda-project

### ISSUE THREAD

**Issue by olsgaard** [holoviz/holoviz#420]
Installing the environment as per the tutorial setup, gives an error, that the tutorial project is not found. Simply including a conda environment yaml file would resolve the issue.

```bash
$ conda --version
conda 23.9.0
$ conda create -n project "anaconda-project>=0.11"
$ conda activate project
$anaconda-project download pyviz/holoviz_tutorial
pyviz/holoviz_tutorial was not found.
```

**Comment by droumis** [comment]
[anaconda.org has removed support for notebooks](https://community.anaconda.cloud/t/notice-upcoming-sunset-of-projects-notebooks-and-environments-features-on-anaconda-org/75989). We'll have to come up with another solution.

**Comment by droumis** [comment]
https://github.com/holoviz/holoviz/pull/424
