### ISSUE TITLE
ESRI ArcGIS tile provider

### ISSUE THREAD

**Issue by AlbertDeFusco** [holoviz/holoviz#54]
In `notebooks/07_Geographic_Data.ipynb` The ESRI URL should have Y before X. Here's the correct URL.

```
'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{Z}/{Y}/{X}.jpg'
```

**Comment by jbednar** [comment]
That explains it!  I had noticed an issue while giving the tutorial, but forgot to get back to it after the tutorial completed. Thanks!
