### ISSUE TITLE
pyviz install fails on new Anaconda3-5.1.0-Linux-x86_64.sh

### ISSUE THREAD

**Issue by boomerTN** [holoviz/holoviz#57]
Hello. I was very excited to find the pyviz.org site and eager to try out the many capabilities it promises. However I am not able to successfully complete Step 3 of the installation instructions on http://pyviz.org/installation.html . I'm using Anaconda3-5.1.0-Linux-x86_64.sh for python.

The error happens on the first part of Step 3.

"pyviz --install-examples pyviz-tutorial"

The pertinent error message is:

AttributeError: module 'pandas' has no attribute 'rolling_count'

I have tried this on 2 different systems, one with Ubuntu 16.04.4 LTS and the other with Ubuntu 18.04 installed with current updates. I get the same response on both systems. 

Subsequently I found the Holoviews tutorial that I could install so I'm busy learning about it. I understand that it is a subset of pyviz and it may well provide the functionality that I'm looking for but I wanted to make you aware of my problem. I say another Issue about Windows 10 but I'm not sure they are related.

I checked the version of pandas that was loaded and found it to be 0.23.0 with conda install providing no newer offering.

**Comment by jbednar** [comment]
pandas 0.23 removed a feature used by other libraries; for now you can install pandas 0.22.  

@philippjfr, I thought you already released new pyviz packages pinning to pandas=0.22?

**Comment by boomerTN** [comment]
Ok, I was able to get the tutorial code and data loaded by "downgrading" pandas to 0.22 and executing steps 3 and 4. I'm afraid I don't quite understand what the pyviz script does but I'm not a bash whiz. I use tcsh because I grew up on the c shell (from Sun Workstation days) and I know most of the tricks. It appears that all pyviz did was download and unpack zip files for the tutorial and the data.

Anyway, I've got it installed and working. I'm pretty excited about it. 

Thanks for the clue.

**Comment by jbednar** [comment]
Ack; we had a miscommunication and the pyviz package was never updated to pin pandas to 0.22!  So sorry about that; @ceball is scrambling to fix that today.  

The pyviz command isn't bash; it is a [Python command-line script](http://python-packaging.readthedocs.io/en/latest/command-line-scripts.html); thankfully we don't have to write any bash or tcsh. (Incidentally, I too still use tcsh for the same reason as you, i.e. coming of age using Sun workstations in the 1990s!)  Yes, all it does is grab the examples and data and make it ready for you to run things.

**Comment by ceball** [comment]
There's now a new package (pyviz-0.9.7-py_1.tar.bz2) on the pyviz channel which pins and/or constrains more dependencies.
