### ISSUE TITLE
NYC Taxi Example Slightly Reworked but inoperable

### ISSUE THREAD

**Issue by TylerTCF** [holoviz/holoviz#61]
Can you tell me if this is a coding problem or an issue?  I seem to always have my heat map show up near NULL Island.  I figured it was a projection problem, so tried to work this per the gv.Points method as well and reproject the data (like some NYC taxi examples).  Have I misapplied the code or did I find a new projection issue?  Thanks.

```
import param, parambokeh
from colorcet import cm_n
from holoviews.streams import RangeXY
from bokeh.tile_providers import STAMEN_TONER

#url='https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{Z}/{X}/{Y}.jpg'
#url='https://maps.wikimedia.org/osm-intl/{Z}/{X}/{Y}.png'
#url='http://c.tile.openstreetmap.org/{Z}/{X}/{Y}.png'
url=STAMEN_TONER
tiles = gv.WMTS(url,crs=crs.GOOGLE_MERCATOR)
opts = dict(width=1000,height=600,xaxis=None,yaxis=None,bgcolor='black',show_grid=False)

class AirTraffic(hv.streams.Stream):
    alpha      = param.Magnitude(default=0.75, doc="Alpha value for the map opacity")
    colormap   = param.ObjectSelector(default=cm_n["fire"], objects=cm_n.values())

    def make_view(self, x_range, y_range, **kwargs):
        map_tiles = tiles.options(alpha=self.alpha, **opts)
        points = hv.Points(ddf, ['lon', 'lat'])
        taxi_trips = datashade(points, cmap=self.colormap,
                               dynamic=False, x_range=x_range, y_range=y_range, width=1000, height=600)
        return map_tiles * taxi_trips

explorer = AirTraffic(name="Russell Traffic")
parambokeh.Widgets(explorer, callback=explorer.event)
hv.DynamicMap(explorer.make_view, streams=[explorer, RangeXY()])
```

Thanks.

**Comment by jbednar** [comment]
I love Null island!  But if it's not what you want, you can probably change 'hv.Points' to 'gv.Points', if the points truly are in lon/lat as the column names would suggest.  That should probably fix projection issues.

**Comment by jbednar** [comment]
Here gv means GeoViews, and GeoViews assumes data is in PlateCaree coordinates (lon/lat) unless otherwise specified, reprojecting as needed for display.  hv means HoloViews, which knows nothing about projecting or geography in general, and thus passes lon/lat values directly to Bokeh for display as Web Mercator, where even the largest lon or lat value is very close to Null Island.

**Comment by TylerTCF** [comment]
I'll rework it with gv and a Mercator projection.  Let me see what happens!

**Comment by TylerTCF** [comment]
James, first of all, it was great to meet you at AnacondaCON!  I'm hoping the tools you developed are what I need!  

The interesting problem I'm having is that with hv.Points a datashade(points) shows the points all plotted in the lat/lons from the dask dataframe.  However, when I move to gv.Points, everything is converted to a region between +/- 0.2 deg in every direction.  I imagine this has to do with the gv conversion to a coordinate system, I just need to figure out where it's wrong I guess.  Should the format for the conversion be points = gv.Points(ddf, kdims=['lon', 'lat'], vdims=['value'], crs.PlateCaree) and then the next line be the datashade(points).  Strange it's working in hv and not gv.  hv version is 1.9.5 and gv version is 1.4.3 if that matters. 
HV Version
![screen shot 2018-06-08 at 2 59 15 pm](https://user-images.githubusercontent.com/34295270/41178334-8a01adb8-6b2c-11e8-823a-9c7aa9df66ff.png)

GV Version 
![screen shot 2018-06-08 at 2 56 04 pm](https://user-images.githubusercontent.com/34295270/41178181-1d9287c4-6b2c-11e8-86ee-fda2b4420281.png)

Slice of ddf
![screen shot 2018-06-08 at 3 00 59 pm](https://user-images.githubusercontent.com/34295270/41178448-db5425b0-6b2c-11e8-861b-d8986bb5c1fe.png)

**Comment by philippjfr** [comment]
Could you try updating to holoviews 1.10.5 and geoviews 1.5.1? They are both available on conda and using pip.

**Comment by TylerTCF** [comment]
Updating and tweaking code slightly got me a tile underneath my points!  Thanks!

I noticed that the app update cycle takes quite some time (~700k rows) as I never was able to see it update (even after several minutes) with the map tile added into the widget.  I was using a 8vCPUs 16GB RAM GCP Ubuntu machine.  

With only a data shade the widget runs in about 6 seconds with the color and alpha update.  Is this normal behavior with the tiles turned on?

```
import param, parambokeh
from colorcet import cm_n
from holoviews.streams import RangeXY
from bokeh.tile_providers import STAMEN_TONER

#url='https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{Z}/{X}/{Y}.jpg'
#url='https://maps.wikimedia.org/osm-intl/{Z}/{X}/{Y}.png'
#url='http://c.tile.openstreetmap.org/{Z}/{X}/{Y}.png'
url=STAMEN_TONER
tiles = gv.WMTS(url,crs=crs.GOOGLE_MERCATOR)
opts = dict(width=1000,height=1000,xaxis=None,yaxis=None,bgcolor='black',show_grid=True)

class AirTraffic(hv.streams.Stream):
    alpha      = param.Magnitude(default=0.75, doc="Alpha value for the map opacity")
    colormap   = param.ObjectSelector(default=cm_n["fire_r"], objects=cm_n.values())

    def make_view(self, x_range, y_range, **kwargs):
        map_tiles = tiles.options(alpha=self.alpha, **opts)
        points = gv.Points(ddf, ['lon', 'lat'])
        taxi_trips = datashade(points, cmap=self.colormap,
                               dynamic=False, x_range=x_range, y_range=y_range, width=1000, height=600)
        return  map_tiles * taxi_trips

explorer = AirTraffic(name="Traffic")
parambokeh.Widgets(explorer, callback=explorer.event)
hv.DynamicMap(explorer.make_view, streams=[explorer, RangeXY()])
```

**Comment by jbednar** [comment]
Hi Tyler!  Based on your plot above, datashader does seem like what your data deserves; just about any other way of showing that data will obscure all the detail that you can see there.

Ordinarily, the tiles shouldn't affect the display speed measurably.  But the tiles only support one projection (Web Mercator), and so if you overlay on tiles then your points have to be reprojected (expensively) before datashader can do its aggregations, every time you compute a plot. So for interactive use you should probably project your points all at once, making subsequent datashading on a tile background much quicker.  @philippjfr can probably suggest a more convenient way, but what I use for reprojecting is the simple `lnglat_to_meters()` function in datashader.util.

**Comment by philippjfr** [comment]
>I noticed that the app update cycle takes quite some time (~700k rows) as I never was able to see it update (even after several minutes) with the map tile added into the widget. I was using a 8vCPUs 16GB RAM GCP Ubuntu machine.

I would suggest projecting the points ahead of time, with:

```python
points = gv.Points(ddf, ['lon', 'lat'])
projected_points = gv.project(points)
```

and then datashade that.

**Comment by TylerTCF** [comment]
Thanks!  Appreciate the issue support.
