### ISSUE TITLE
Repo structure

### ISSUE THREAD

**Issue by jbednar** [holoviz/holoviz#63]
Right now, the pyviz repo has a different structure than our other projects.  Standard projects put every notebook or app the user can run into `./examples`:

- ./examples/getting-started
- ./examples/user-guide
- ./examples/topics

PyViz puts things at the top level, and also publishes them at a different spot on the website:

- ./notebooks : tutorial notebooks (appears under `/tutorial' on the website)
- ./apps: tutorial apps
- ./exercises: tutorial exercises

We are planning to add `topics`  to PyViz, and in general things are easier if we make things uniform, so I propose that we put everything in `./examples` on PyViz like in the other projects:

- ./examples/tutorial/
- ./examples/tutorial/apps (maybe?)
- ./examples/tutorial/exercises (maybe?)
- ./examples/topics/

The website can then still use the same `tutorial` subdirectory as it does now, so it seems like this shouldn't affect existing links, and it makes the website map more clearly onto the repo (at least for those used to the `examples` directory idea).

Any votes for or against or for a modified proposal?

**Comment by jlstevens** [comment]
I vote in favor of this proposal as I prefer consistency.

**Comment by philippjfr** [comment]
+1 for consistency.
