### ISSUE TITLE
holoviz versioning/releasing

### ISSUE THREAD

**Issue by ceball** [holoviz/holoviz#78]
I think my question is, how should holoviz be released? I.e. when do we make packages, and when do we update the website? Maybe:
* tag like v0.1.2: website build to holoviz.org, conda package to pyviz/label/main
* tag like v0.1.2a3: website build to https://pyviz-dev.github.io/, conda package to pyviz/label/dev
* update to master: website build to https://holoviz.github.io/holoviz-master

Is that enough to support what we want for now? Or e.g. is it necessary to be able to update the website without releasing packages? And I'm assuming we don't yet need to keep around versioned docs for pyviz (though we could).

(Maybe the pyviz-dev website and possibly even the packages could be linked somewhere from the readme. Maybe even the holoviz-master website would be a useful link to have, for developers.)

**Comment by jbednar** [comment]
1. We need versioned docs eventually but they don't seem like the top priority right now.  
2. Renaming ioam-docs to pyviz-docs would be great, thanks. [done]
3. Linking the dev and master packages and website from the Github readme would be great; they shouldn't be linked from pyviz.org, but anyone looking at github should be able to handle the idea of master and dev releases.
4. I think we need a fourth option to the above, i.e. some way to trigger an update to the website independently of the release process (either just after a release as we fix errata, or in between releases where we put notes about known issues that emerge or update the install instructions to pin certain packages that we discover should have been pinned).  Maybe a special tag like "docbuild" that when made on a PR branch updates https://ioam-docs.github.io/pyviz-dev, and when made on master updates pyviz.org?

**Comment by jbednar** [comment]
I think these are essentially all done, in some form.
