### ISSUE TITLE
What pyviz packages should there be?

### ISSUE THREAD

**Issue by ceball** [holoviz/holoviz#86]
(I thought I already created this issue, but apparently not. If I missed a duplicate issue, or we discussed this elsewhere and I've forgotten to import the discussion here, please close or edit this issue...)

Currently we have one pyviz package, with dependencies for all the topics. We don't yet list topics, but will soon. At that point, should we have multiple packages (i.e. options), with each corresponding to a topic?

Also: we currently produce only a highly pinned conda package. That's ok, because pyviz isn't a library that's designed to be integrated into someone else's package (that's what the libraries underling pyviz are for). But a highly pinned conda package can be difficult to install, except in a dedicated environment. By which point, a "conda env create (some file env file on anaconda.org or maybe github)" command might make more sense...?

**Comment by jsignell** [comment]
It could be nice to have each topic notebook have it's own mini env that would depend on pyviz core but add any additional packages and could be used with `conda env update -f <topic-env-file>`

**Comment by jsignell** [comment]
I think we have resolved this somewhat by saying holoviz is a highly pinned set of packages that are guaranteed to work together, but not guaranteed to be up to date. Then there is pyviz-topics/examples which uses the anaconda-project approach.
